/**
 * Builds the design book into framework-agnostic artifacts.
 *
 * Nothing here is specific to a UI framework: the outputs are plain CSS custom
 * properties, plain JSON, the W3C Design Tokens format, and a dependency-free
 * ESM module. `design-book` is only needed at build time — consumers of the
 * published package never import it.
 */
import { mkdir, rm, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join, resolve } from 'node:path'

import { Renderer } from 'design-book'
import type { W3DesignTokensMap, W3TokenEntry } from 'design-book'
import { book, rampNames, rampShades } from '../src/pmndrs-design-book.js'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outDir = join(root, 'dist')

const banner = `/* ${book.name} design tokens — generated by scripts/build.ts. Do not edit. */`

/**
 * Webfonts backing the `fonts.*` tokens, in Google Fonts `css2` syntax.
 *
 * Emitted as a separate `dist/fonts.css` rather than folded into
 * `tokens.css`: importing the token layer should never force a third-party
 * request on a consumer who self-hosts these families or has already loaded
 * them. Keep this list in step with the `fonts` scope in the design book.
 */
const webfonts = [
	'Faculty Glyphic', // fonts.serif — single weight
	'Geist:wght@100..900', // fonts.sans — variable
	'Geist Mono:wght@100..900', // fonts.mono — variable
]

function fontsStylesheet() {
	const families = webfonts.map((family) => `family=${family.replace(/ /g, '+')}`).join('&')

	return `${banner}
@import url('https://fonts.googleapis.com/css2?${families}&display=swap');
`
}

/**
 * Fixed stop positions for the gradient generator, as a percentage of the
 * gradient line. Symmetrical around the midpoint, with the outer stops pulled
 * inward so each colour holds a flat band before it starts blending.
 */
const gradientStops = [16, 50, 84] as const

/** Brand tokens excluded from gradients — the neutral ground colours. */
const gradientExclusions = new Set(['brand.dark', 'brand.light'])

/**
 * Token paths whose value is a colour, according to the book itself. Asking
 * `inspect` beats pattern-matching the rendered value, which would silently
 * miss colours the moment the authored notation changes (hex -> oklab -> oklch -> ...).
 *
 * Two shapes count. A literal colour reports `tokenType: 'color'`; a computed
 * one — every ramp step is a `ramp()` call — reports `tokenType: 'function'`
 * and declares its `returnType` instead. Checking only the first would drop
 * the entire ramp scope on the floor.
 */
function colorPaths(paths: string[]) {
	return paths.filter((path) => {
		const token = book.inspect(path)
		return token?.tokenType === 'color' || token?.returnType === 'color'
	})
}

/**
 * Colours a gradient stop may use: every colour token in the `brand` scope
 * except the neutrals. Derived from the book rather than hand-listed, so a new
 * brand colour becomes selectable on the next build.
 */
function gradientPalette(paths: string[]) {
	return colorPaths(paths).filter(
		(path) => path.startsWith('brand.') && !gradientExclusions.has(path),
	)
}

/**
 * For each ramp, the step whose value *is* the brand colour.
 *
 * The dittotones engine places a seed at whichever step it perceptually
 * belongs to rather than forcing it to the middle, so `brand.purple` lands on
 * `500` while the much lighter `brand.teal` lands on `300`. Knowing that step
 * is what lets a consumer walk a ramp relative to the brand value — "two steps
 * darker than the brand teal" — instead of guessing at 500.
 *
 * Found by comparing rendered hex rather than assumed: if a future seed
 * doesn't survive its own ramp exactly, the build says so instead of shipping
 * a wrong answer.
 */
function rampSeedShades(w3c: W3DesignTokensMap) {
	const hex = (group: string, name: string) => {
		const value = (w3c[group] as Record<string, W3TokenEntry> | undefined)?.[name]?.$value
		return typeof value === 'object' && value && 'hex' in value
			? String((value as { hex?: string }).hex).toLowerCase()
			: undefined
	}

	return Object.fromEntries(
		rampNames.map((name) => {
			const seed = hex('brand', name)
			const shade = rampShades.find((step) => hex('ramp', `${name}-${step}`) === seed)

			if (!shade) {
				throw new Error(
					`brand.${name} (${seed}) does not appear in its own ramp. The ramp engine no longer round-trips its seed — check the design-book version before shipping.`,
				)
			}

			return [name, shade]
		}),
	)
}

const jsonModule = (tokens: Record<string, string>, seedShades: Record<string, string>) => {
	const paths = Object.keys(tokens)
	const union = paths.map((p) => `'${p}'`).join('\n\t| ')

	const colors = colorPaths(paths)
	const colorUnion = colors.map((p) => `'${p}'`).join('\n\t| ')
	const palette = gradientPalette(paths)
	const paletteUnion = palette.map((p) => `'${p}'`).join('\n\t| ')

	const js = `${banner}

/** Fully resolved token values. References are flattened to literals. */
export const tokens = Object.freeze(${JSON.stringify(tokens, null, '\t')})

/** Every token path, in declaration order. */
export const tokenPaths = Object.freeze(${JSON.stringify(paths, null, '\t')})

/** \`brand.dark\` -> \`--brand-dark\` */
export function varName(path) {
\treturn \`--\${path.replace(/\\./g, '-')}\`
}

/**
 * \`brand.dark\` -> \`var(--brand-dark)\`. Use this in inline styles or
 * CSS-in-JS so values stay live and themable; use \`tokens\` when you need a
 * concrete value (canvas, WebGL, a chart library, ...).
 */
export function cssVar(path, fallback) {
\treturn fallback === undefined
\t\t? \`var(\${varName(path)})\`
\t\t: \`var(\${varName(path)}, \${fallback})\`
}

/**
 * Paths whose value is a colour, in declaration order. Classified by the
 * design book at build time, so this stays correct regardless of the notation
 * the values are authored in.
 */
export const colorPaths = Object.freeze(${JSON.stringify(colors, null, '\t')})

/** Ramp names — one per brand colour, accents and neutrals alike. */
export const rampNames = Object.freeze(${JSON.stringify(rampNames, null, '\t')})

/** Ramp steps, light to dark. */
export const rampShades = Object.freeze(${JSON.stringify(rampShades, null, '\t')})

/**
 * Ramp name -> the step that holds the brand colour exactly. The engine places
 * a seed by perceived lightness rather than at a fixed step, so this is 500 for
 * \`purple\` but 300 for the much lighter \`teal\`. Use it to walk a ramp
 * relative to the brand value instead of assuming the middle.
 */
export const rampSeeds = Object.freeze(${JSON.stringify(seedShades, null, '\t')})

/**
 * \`('purple', '500')\` -> \`'ramp.purple-500'\`. Compose it with \`tokens\`
 * or \`cssVar\` rather than building the string by hand, so a typo fails here
 * instead of silently resolving to \`undefined\` further down.
 */
export function rampPath(name, shade) {
\tif (!rampNames.includes(name)) {
\t\tthrow new RangeError(
\t\t\t\`'\${name}' is not a ramp. Choose one of: \${rampNames.join(', ')}\`,
\t\t)
\t}
\tif (!rampShades.includes(shade)) {
\t\tthrow new RangeError(
\t\t\t\`'\${shade}' is not a ramp step. Choose one of: \${rampShades.join(', ')}\`,
\t\t)
\t}

\treturn \`ramp.\${name}-\${shade}\`
}

/** Stop positions, as percentages along the gradient line. */
export const gradientStops = Object.freeze(${JSON.stringify(gradientStops)})

/**
 * Colours a gradient stop may use — the brand colours, minus the neutrals
 * (\`brand.dark\` / \`brand.light\`), which are the page ground rather than
 * accents.
 */
export const gradientColors = Object.freeze(${JSON.stringify(palette, null, '\t')})

/**
 * Throws unless \`stops\` is a legal selection: one colour per stop, each from
 * \`gradientColors\`, and no two *adjacent* stops the same. Repeats are allowed
 * at a distance, so first and last may match — that yields a symmetrical
 * gradient rather than a degenerate one.
 */
export function assertGradientStops(stops) {
\tif (!Array.isArray(stops) || stops.length !== gradientStops.length) {
\t\tthrow new TypeError(
\t\t\t\`gradient() expects exactly \${gradientStops.length} stops, received \${
\t\t\t\tArray.isArray(stops) ? stops.length : typeof stops
\t\t\t}\`,
\t\t)
\t}

\tstops.forEach((path, i) => {
\t\tif (!gradientColors.includes(path)) {
\t\t\tthrow new RangeError(
\t\t\t\t\`Stop \${i + 1} is '\${path}', which is not a gradient colour. Choose one of: \${gradientColors.join(', ')}\`,
\t\t\t)
\t\t}
\t\tif (i > 0 && stops[i - 1] === path) {
\t\t\tthrow new RangeError(
\t\t\t\t\`Stops \${i} and \${i + 1} are both '\${path}'. Adjacent stops must differ.\`,
\t\t\t)
\t\t}
\t})
}

/**
 * Builds a three-stop \`linear-gradient()\` from brand colours.
 *
 * Stops emit as \`var(--brand-*)\` by default so the gradient re-renders when a
 * token is themed; pass \`resolve: true\` for literal colour values when the
 * consumer can't read custom properties (canvas, WebGL, PDF).
 */
export function gradient(stops, options = {}) {
\tassertGradientStops(stops)
\tconst { angle = '90deg', resolve = false } = options

\tconst parts = stops.map(
\t\t(path, i) => \`\${resolve ? tokens[path] : cssVar(path)} \${gradientStops[i]}%\`,
\t)

\treturn \`linear-gradient(\${angle}, \${parts.join(', ')})\`
}

/**
 * A random legal gradient. Each stop is drawn from the palette minus its
 * predecessor, so the adjacency rule holds by construction rather than by
 * retrying until a valid combination turns up.
 *
 * Pass \`random\` (any \`() => number\` in [0, 1)) to make the result
 * reproducible in tests.
 */
export function randomGradient(options = {}) {
\tconst { random = Math.random, ...rest } = options

\tconst stops = []
\tfor (let i = 0; i < gradientStops.length; i++) {
\t\tconst choices = gradientColors.filter((path) => path !== stops[i - 1])
\t\tconst index = Math.min(choices.length - 1, Math.floor(random() * choices.length))
\t\tstops.push(choices[index])
\t}

\treturn gradient(stops, rest)
}
`

	const dts = `${banner}

/** Every token path defined in the design book. */
export type TokenPath =
\t| ${union}

/** Fully resolved token values. References are flattened to literals. */
export declare const tokens: Readonly<Record<TokenPath, string>>

/** Every token path, in declaration order. */
export declare const tokenPaths: readonly TokenPath[]

/** \`brand.dark\` -> \`--brand-dark\` */
export declare function varName(path: TokenPath): string

/**
 * \`brand.dark\` -> \`var(--brand-dark)\`. Use this in inline styles or
 * CSS-in-JS so values stay live and themable; use \`tokens\` when you need a
 * concrete value (canvas, WebGL, a chart library, ...).
 */
export declare function cssVar(path: TokenPath, fallback?: string): string

/** A token path whose value is a colour. */
export type ColorPath =
\t| ${colorUnion}

/**
 * Paths whose value is a colour, in declaration order. Classified by the
 * design book at build time, so this stays correct regardless of the notation
 * the values are authored in.
 */
export declare const colorPaths: readonly ColorPath[]

/** A colour that has a ramp — every brand colour, neutrals included. */
export type RampName =
\t| ${rampNames.map((n) => `'${n}'`).join('\n\t| ')}

/** A step of a ramp, light to dark. */
export type RampShade =
\t| ${rampShades.map((s) => `'${s}'`).join('\n\t| ')}

/** A single ramp step, e.g. \`'ramp.purple-500'\`. A subset of \`ColorPath\`. */
export type RampPath = \`ramp.\${RampName}-\${RampShade}\`

/** Ramp names — one per brand colour, accents and neutrals alike. */
export declare const rampNames: readonly RampName[]

/** Ramp steps, light to dark. */
export declare const rampShades: readonly RampShade[]

/**
 * Ramp name -> the step that holds the brand colour exactly. The engine places
 * a seed by perceived lightness rather than at a fixed step, so this is 500 for
 * \`purple\` but 300 for the much lighter \`teal\`.
 */
export declare const rampSeeds: Readonly<Record<RampName, RampShade>>

/**
 * \`('purple', '500')\` -> \`'ramp.purple-500'\`. Compose it with \`tokens\`
 * or \`cssVar\` rather than building the string by hand.
 */
export declare function rampPath(name: RampName, shade: RampShade): RampPath

/** A brand colour eligible for a gradient stop. Excludes the neutrals. */
export type GradientColor =
\t| ${paletteUnion}

/**
 * One colour per stop. The type fixes the arity; the *adjacency* rule (no two
 * neighbouring stops alike) is enforced at runtime by \`assertGradientStops\`,
 * since it can't be expressed here without an unusable combinatorial union.
 */
export type GradientStopSelection = readonly [${palette.length > 0 ? gradientStops.map(() => 'GradientColor').join(', ') : ''}]

export interface GradientOptions {
\t/** Any CSS \`<angle>\` or side-or-corner keyword. Defaults to \`'90deg'\`. */
\tangle?: string
\t/**
\t * Emit literal colour values instead of \`var(--brand-*)\` references.
\t * Defaults to \`false\`; set it for canvases and other non-CSS targets.
\t */
\tresolve?: boolean
}

/** Stop positions, as percentages along the gradient line. */
export declare const gradientStops: readonly [${gradientStops.join(', ')}]

/** Colours a gradient stop may use — the brand colours, minus the neutrals. */
export declare const gradientColors: readonly GradientColor[]

/** Throws unless \`stops\` is a legal selection. See \`gradient\`. */
export declare function assertGradientStops(
\tstops: GradientStopSelection,
): asserts stops is GradientStopSelection

/** Builds a three-stop \`linear-gradient()\` from brand colours. */
export declare function gradient(
\tstops: GradientStopSelection,
\toptions?: GradientOptions,
): string

/** A random legal gradient. Pass \`random\` for reproducible output. */
export declare function randomGradient(
\toptions?: GradientOptions & { random?: () => number },
): string
`

	return { js, dts }
}

async function build() {
	await rm(outDir, { recursive: true, force: true })
	await mkdir(outDir, { recursive: true })

	const tokens = new Renderer(book, 'json').renderJsonObject()

	/* Rendered once and reused: it's the only output that carries hex for every
	   colour, which is what `rampSeedShades` compares against. */
	const w3c = book.render('w3-design-tokens')
	const { js, dts } = jsonModule(tokens, rampSeedShades(JSON.parse(w3c) as W3DesignTokensMap))

	const artifacts: Array<[string, string]> = [
		['tokens.css', `${banner}\n${book.render('css-variables')}\n`],
		['fonts.css', fontsStylesheet()],
		['tokens.json', `${JSON.stringify(tokens, null, '\t')}\n`],
		['tokens.w3c.json', `${w3c}\n`],
		['tokens.js', js],
		['tokens.d.ts', dts],
	]

	await Promise.all(
		artifacts.map(([name, contents]) => writeFile(join(outDir, name), contents, 'utf8')),
	)

	const count = Object.keys(tokens).length
	console.log(`${book.name}: ${count} tokens -> dist/`)
	for (const [name] of artifacts) console.log(`  dist/${name}`)
}

await build()
