/**
 * figma-page — puts `demo/index.html` into the round trip.
 *
 * Same split as `figma-push.ts`: this file decides *what* the Figma page should
 * contain and emits a self-contained program that makes it so; `use_figma` runs
 * it; `--record` folds the returned ids back into `figma/sync.json`.
 *
 * The rule that matters is in the generated program's `instance()`: a block the
 * page spec marks as a component becomes `createInstance()` of the component
 * already in the file, with its variant set from the props the page renders.
 * Nothing about a Gha's fill or a Button's radius is restated here — those live
 * in the component, which lives in Figma, which is bound to the variables the
 * token push wrote. Drawing them again would give the design system a second
 * definition whose only synchroniser is whoever last looked at both.
 *
 *   pnpm figma:page                  # emit dist/figma-page.{json,js} + a summary
 *   pnpm figma:page --snapshot       # also emit the read-back program
 *   pnpm figma:page --record out.json
 */
import { readFile, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'

import { flag, has } from './figma/args.js'
import { describe, extractPage, instancesOf, paths, type PageSpec } from './figma/page.js'
import { readState, writeState } from './figma/state.js'
import { families } from '../src/pmndrs-design-book.js'

const SOURCE = 'demo/index.html'
const SPEC_PATH = resolve(process.cwd(), 'dist', 'figma-page.json')
const OUT_PATH = resolve(process.cwd(), 'dist', 'figma-page.js')
const SNAPSHOT_PATH = resolve(process.cwd(), 'dist', 'figma-page-snapshot.js')

const FRAME_NAME = SOURCE

/**
 * The faces the page loads, as Figma `{ family, style }` pairs.
 *
 * The families come from the design book — this file used to spell them out a
 * second time, which is how a typeface could be renamed in the tokens and
 * still be requested here under its old name. The *styles* stay local: which
 * weight a heading or an alert is set in is a decision this page makes, not
 * something the token book knows. `sansMedium` is the same family as `sans` at
 * a different weight, which is exactly why family and style are separate.
 */
const FACES = {
	serif: { family: families.serif, style: 'Regular' },
	sans: { family: families.sans, style: 'Regular' },
	sansMedium: { family: families.sans, style: 'Medium' },
	mono: { family: families.mono, style: 'Regular' },
	legible: { family: families.legible, style: 'ExtraBold' },
}

/**
 * The program that runs inside Figma.
 *
 * Written as one string for the same reason the token push is: the plugin
 * sandbox has no filesystem and no network back to this repo, so everything it
 * needs — the spec, the component ids, the layout rules — travels with it.
 */
function pluginScript(spec: PageSpec, components: Record<string, string>, where: Target) {
	return `// generated by scripts/figma-page.ts — do not edit
const SPEC = ${JSON.stringify(spec)}
const COMPONENTS = ${JSON.stringify(components)}
const FRAME_ID = ${JSON.stringify(where.frameId ?? null)}
const PAGE_IDS = ${JSON.stringify(where.pageIds)}
const FRAME_NAME = ${JSON.stringify(FRAME_NAME)}
const WIDTH = 1200

/* ---------- fonts ---------- */

// The families the token book names. A file that somehow lacks one falls back
// to Inter rather than failing the whole page: a missing typeface is a visible
// problem, not a reason to ship no layout at all.
const WANTED = ${JSON.stringify(FACES)}
const FALLBACK = { family: 'Inter', style: 'Regular' }
/** Widest a text node is measured at before it is told to fill its parent. */
const MAX_TEXT_WIDTH = WIDTH
const FONTS = {}
const missingFonts = []
for (const [key, font] of Object.entries(WANTED)) {
  try {
    await figma.loadFontAsync(font)
    FONTS[key] = font
  } catch {
    missingFonts.push(font.family + ' ' + font.style)
    FONTS[key] = FALLBACK
  }
}
await figma.loadFontAsync(FALLBACK)

/* ---------- variables ---------- */

const allVariables = await figma.variables.getLocalVariablesAsync()
// Keyed both ways, because a variable wears its collection in one of two
// places: as a prefix on its own name ('theme/page'), or as the collection it
// sits in, under a bare name ('page' in 'theme'). Which one a file uses is
// Figma's business — this file is the second kind — so qualify every variable
// with its collection and keep its literal name as a fallback.
const collectionNames = new Map(
  (await figma.variables.getLocalVariableCollectionsAsync()).map((c) => [c.id, c.name]),
)
const variableByName = new Map()
for (const v of allVariables) {
  if (!variableByName.has(v.name)) variableByName.set(v.name, v)
  variableByName.set((collectionNames.get(v.variableCollectionId) || '') + '/' + v.name, v)
}
const missingVariables = new Set()

function variable(name) {
  const found = variableByName.get(name)
  if (!found) missingVariables.add(name)
  return found || null
}

/** Paints the node from a variable, so the page follows the mode like the components do. */
function fill(node, name) {
  const v = variable(name)
  if (!v) return node
  node.fills = [figma.variables.setBoundVariableForPaint(figma.util.solidPaint('#808080'), 'color', v)]
  return node
}

function stroke(node, name, weight) {
  const v = variable(name)
  if (!v) return node
  node.strokes = [figma.variables.setBoundVariableForPaint(figma.util.solidPaint('#808080'), 'color', v)]
  node.strokeWeight = weight || 1
  return node
}

/* ---------- primitives ---------- */

function frame(name, opts, existing) {
  const options = opts || {}
  // An existing node is re-used rather than replaced: see the assemble step.
  const node = existing || figma.createFrame()
  node.name = name
  // Before the sizing modes, not after: resize() resets them to FIXED, so a
  // frame given a width last would stop hugging its own content.
  if (options.width != null) node.resize(options.width, 100)
  node.layoutMode = options.row ? 'HORIZONTAL' : 'VERTICAL'
  node.primaryAxisSizingMode = 'AUTO'
  node.counterAxisSizingMode = options.hug ? 'AUTO' : 'FIXED'
  node.itemSpacing = options.gap == null ? 12 : options.gap
  node.paddingTop = node.paddingBottom = options.padY == null ? 0 : options.padY
  node.paddingLeft = node.paddingRight = options.padX == null ? 0 : options.padX
  node.fills = []
  if (options.wrap) {
    node.layoutWrap = 'WRAP'
    node.counterAxisSpacing = options.gap == null ? 12 : options.gap
  }
  if (options.align) node.counterAxisAlignItems = options.align
  if (options.surface) fill(node, options.surface)
  if (options.line) stroke(node, options.line, options.strokeWeight)
  if (options.radius != null) node.cornerRadius = options.radius
  return node
}

function text(chars, opts) {
  const options = opts || {}
  const node = figma.createText()
  node.fontName = FONTS[options.font || 'sans']
  node.fontSize = options.size || 14
  node.lineHeight = { unit: 'PERCENT', value: options.leading || 150 }
  // Order is the whole trick. A text node switched to HEIGHT before it has any
  // characters keeps a zero width, and telling it to FILL afterwards does not
  // rescue it — it lays out one character per line and grows to thousands of
  // pixels. So: set the characters while it still sizes to its content, take
  // that width, and only then let it grow downward.
  // Letter spacing first: it widens the text, and measuring before it is applied
  // leaves the node a few pixels short — enough to wrap a one-line eyebrow.
  if (options.letterSpacing) node.letterSpacing = { unit: 'PIXELS', value: options.letterSpacing }
  node.characters = chars || ' '
  const measured = Math.max(1, Math.min(node.width, MAX_TEXT_WIDTH))
  node.textAutoResize = 'HEIGHT'
  node.resize(measured, node.height)
  fill(node, 'theme/' + (options.slot || 'text-body'))
  return node
}

/**
 * Appends, then stretches to the parent's width.
 *
 * Order matters: FILL is only legal once the node is a child of an auto-layout
 * frame. A null sizing means leave the node's own sizing alone — what a Button or a
 * Badge wants, since their width is the component's decision.
 */
function add(parent, child, sizing) {
  parent.appendChild(child)
  if (sizing === null) return child
  try {
    child.layoutSizingHorizontal = sizing || 'FILL'
  } catch {
    /* Absolute, grid, and immutable children can't fill; leave them as they are. */
  }
  return child
}

/* ---------- instances ---------- */

const placed = []
const problems = []

/** Components the page lays out full-width. */
const WIDE = new Set(['Gha', 'Code', 'Header'])

/**
 * One component instance, from the component already in this file.
 *
 * The variant comes from the page's own props. Text that the page overrides is
 * written onto the instance's layers by *semantic* name — body, title, label —
 * which is the only Figma-specific knowledge in the whole pipeline.
 */
const TEXT_LAYERS = { body: 'body', title: 'title', label: 'label' }

async function instance(block, path) {
  const id = COMPONENTS[block.component]
  if (!id) {
    problems.push(path + ': no Figma component recorded for ' + block.component)
    return null
  }

  const node = await figma.getNodeByIdAsync(id)
  if (!node || (node.type !== 'COMPONENT_SET' && node.type !== 'COMPONENT')) {
    problems.push(path + ': ' + id + ' is not a component')
    return null
  }

  const source = node.type === 'COMPONENT_SET' ? node.defaultVariant : node
  const inst = source.createInstance()

  // Only the props that are variant axes in Figma. showLineNumbers and
  // highlight are code-side props of the same component — the contract says so
  // — and asking Figma for a variant it never declared should say that, not
  // silently place the default.
  const axes = node.type === 'COMPONENT_SET' ? Object.keys(node.componentPropertyDefinitions) : []
  const wanted = {}
  for (const [prop, value] of Object.entries(block.props || {})) {
    if (!axes.includes(prop)) continue
    wanted[prop] = typeof value === 'boolean' ? (value ? 'True' : 'False') : String(value)
  }
  if (Object.keys(wanted).length) {
    try {
      inst.setProperties(wanted)
    } catch (error) {
      problems.push(path + ': ' + String(error.message || error))
    }
  }

  const texts = inst.findAllWithCriteria({ types: ['TEXT'] })
  for (const [slot, chars] of Object.entries(block.text || {})) {
    const layer = TEXT_LAYERS[slot]
    const target = texts.find((t) => t.name === layer)
    if (!target) {
      problems.push(path + ': ' + block.component + ' has no "' + layer + '" text layer')
      continue
    }
    // A layer's copy can be driven by a TEXT component property — Eyebrow's is.
    // Writing characters straight onto one of those is the wrong door: the
    // property is what the instance renders, so an override placed on the layer
    // is either refused or quietly overwritten by the property's value.
    const property = target.componentPropertyReferences && target.componentPropertyReferences.characters
    if (property) {
      try {
        inst.setProperties({ [property]: chars })
      } catch (error) {
        problems.push(path + ': ' + String(error.message || error))
      }
      continue
    }
    await setCharacters(target, chars)
  }

  // showLineNumbers=150 means the gutter counts from 150. The component's rows
  // are numbered from 1, so the override is per row rather than a property.
  if (block.gutterStart != null && block.gutterStart !== 1) {
    const gutters = texts.filter((t) => t.name === 'gutter')
    // The gutter is a column sized for one digit. Three-digit numbers have to
    // widen it, or "150" wraps into "15" over "0" and the code reads as
    // nonsense — which is worse than not numbering it at all.
    for (let i = 0; i < gutters.length; i++) await setCharacters(gutters[i], String(block.gutterStart + i), true)
  }

  placed.push({ path, component: block.component, props: block.props || {}, id: inst.id })
  return inst
}

async function setCharacters(node, chars, grow) {
  const font = node.fontName
  if (font === figma.mixed) {
    for (let i = 0; i < node.characters.length; i++) await figma.loadFontAsync(node.getRangeFontName(i, i + 1))
  } else {
    await figma.loadFontAsync(font)
  }
  if (grow) node.textAutoResize = 'WIDTH_AND_HEIGHT'
  node.characters = chars
}

/* ---------- generated content ---------- */

const BRAND = ['dark', 'light', 'purple', 'red', 'orange', 'yellow', 'green', 'teal', 'blue']
const RAMPS = ['dark', 'light', 'purple', 'red', 'orange', 'yellow', 'green', 'teal', 'blue']
const SHADES = ['50', '100', '200', '300', '400', '500', '600', '700', '800', '900', '950']

/** The palette, drawn from the brand variables rather than from copied hexes. */
function swatches() {
  const row = frame('swatches', { row: true, gap: 12, wrap: true })
  for (const name of BRAND) {
    const cell = frame(name, { gap: 8, hug: true })
    const chip = figma.createRectangle()
    chip.name = name
    chip.resize(112, 72)
    chip.cornerRadius = 12
    fill(chip, 'brand/' + name)
    cell.appendChild(chip)
    cell.appendChild(text('brand.' + name, { font: 'mono', size: 11, slot: 'text-faint' }))
    row.appendChild(cell)
  }
  return row
}

/** Eleven steps per ramp, each bound to its own variable. */
function ramps() {
  const stack = frame('ramps', { gap: 8 })
  for (const name of RAMPS) {
    const row = frame(name, { row: true, gap: 0, align: 'CENTER' })
    const label = text(name, { font: 'mono', size: 11, slot: 'text-faint' })
    row.appendChild(label)
    label.resize(64, label.height)
    label.textAutoResize = 'HEIGHT'
    for (const shade of SHADES) {
      const cell = figma.createRectangle()
      cell.name = name + '-' + shade
      cell.resize(88, 32)
      fill(cell, 'ramp/' + name + '-' + shade)
      row.appendChild(cell)
    }
    add(stack, row)
  }
  return stack
}

/**
 * A specimen with no contract component.
 *
 * Deliberately a label rather than a drawing. Everything the contract declares
 * is an instance a few lines above; a hand-drawn Figma version of the rest
 * would be a design nobody owns in code, and the audit could never tell whether
 * it had drifted because there would be nothing to compare it to.
 */
function standin(block) {
  const box = frame('standin:' + block.name, {
    gap: 4,
    padY: 20,
    padX: 20,
    surface: 'theme/surface-raised',
    line: 'theme/line',
    radius: 8,
    align: 'CENTER',
  })
  box.dashPattern = [4, 4]
  box.appendChild(text(block.name, { font: 'mono', size: 12, slot: 'text-muted' }))
  box.appendChild(text('no contract component — rendered in code only', { size: 11, slot: 'text-faint' }))
  return box
}

/* ---------- blocks ---------- */

async function render(parent, block, path) {
  switch (block.kind) {
    case 'hero': {
      const box = frame('hero', { gap: 16, padY: 24 })
      add(parent, box)
      // Loose text only when the page hasn't marked its eyebrow as a component;
      // when it has, the instance below carries the same words as an override.
      const marked = (block.children || []).some((c) => c.kind === 'instance' && c.component === 'Eyebrow')
      if (!marked) box.appendChild(text(block.eyebrow, { font: 'mono', size: 12, slot: 'text-faint', letterSpacing: 1 }))
      await children(box, block.children, path)
      // The hero's own copy, in the frame the page declares for it. Filled after
      // the children so it lands inside that frame rather than beside it.
      const intro = box.children.find((n) => n.name === 'hero-intro')
      if (intro) {
        add(intro, text(block.heading.join('\\n'), { font: 'legible', size: 72, slot: 'text', leading: 95 }))
        add(intro, text(block.lede, { size: 18, slot: 'text-muted' }))
      }
      return box
    }
    case 'section': {
      const box = frame('section#' + block.id, { gap: 20, padY: 20 })
      add(parent, box)
      if (block.heading) add(box, text(block.heading, { font: 'serif', size: 36, slot: 'text' }))
      await children(box, block.children, path)
      return box
    }
    case 'row': {
      // Vertical where the page stacks (the hero's copy, the waterfall, a
      // spec's stage), a wrapping row everywhere else — which is what the CSS
      // does too. The gap goes with the stacking, so both live in one table.
      const STACKED = { 'hero-intro': 12, waterfall: 48, stage: 48 }
      const stacked = block.name in STACKED
      const box = frame(block.name, { gap: stacked ? STACKED[block.name] : 12, row: !stacked, wrap: !stacked })
      add(parent, box)
      await children(box, block.children, path)
      return box
    }
    case 'group': {
      const box = frame('group:' + block.label, { gap: 20 })
      add(parent, box)
      add(box, text(block.label.toUpperCase(), { font: 'mono', size: 11, slot: 'text-faint', letterSpacing: 1 }))
      await children(box, block.children, path)
      return box
    }
    case 'spec': {
      const box = frame('spec:' + block.label, {
        gap: 12,
        padY: 20,
        padX: 20,
        surface: 'theme/surface',
        line: 'theme/line-soft',
        radius: 12,
      })
      add(parent, box)
      const head = frame('head', { row: true, gap: 8, hug: true })
      box.appendChild(head)
      head.appendChild(text(block.label, { font: 'mono', size: 14, slot: 'text' }))
      if (block.tag) {
        const tag = frame('tag', { row: true, padX: 8, padY: 2, hug: true, surface: 'theme/surface-sunken', radius: 999 })
        tag.appendChild(text(block.tag, { font: 'mono', size: 10, slot: 'text-faint' }))
        head.appendChild(tag)
      }
      if (block.description) add(box, text(block.description, { size: 13, slot: 'text-muted' }))
      await children(box, block.children, path)
      return box
    }
    case 'instance': {
      const inst = await instance(block, path)
      // A callout, a code block and the masthead are full-width in the page, so
      // they are here too. A button or a badge is sized by its own content.
      if (inst) add(parent, inst, WIDE.has(block.component) ? 'FILL' : null)
      return inst
    }
    case 'standin':
      return add(parent, standin(block))
    case 'note': {
      // Named, unlike every other text node here. A note is a block the page
      // composes with, so it needs an address; the prose inside a card is not.
      const note = text(block.text, { size: 14, slot: 'text-muted' })
      note.name = 'note'
      return add(parent, note)
    }
    case 'swatches':
      return add(parent, swatches())
    case 'ramps':
      return add(parent, ramps())
    case 'typeSpecimens': {
      const row = frame('typeSpecimens', { row: true, gap: 24 })
      add(parent, row)
      for (const item of block.items) {
        const cell = frame(item.caption, { gap: 8, padY: 20, padX: 20, surface: 'theme/surface', radius: 12 })
        add(row, cell)
        cell.appendChild(text(item.sample, { font: item.font === 'serif' ? 'serif' : item.font === 'mono' ? 'mono' : 'sans', size: 28, slot: 'text' }))
        cell.appendChild(text(item.caption, { font: 'mono', size: 11, slot: 'text-faint' }))
      }
      return row
    }
    case 'snippet': {
      const box = frame('snippet:' + block.caption, {
        gap: 12,
        padY: 16,
        padX: 16,
        surface: 'theme/surface-sunken',
        radius: 12,
      })
      add(parent, box)
      add(box, text(block.caption, { font: 'mono', size: 11, slot: 'text-faint' }))
      add(box, text(block.code, { font: 'mono', size: 13, slot: 'text-body', leading: 160 }))
      return box
    }
    case 'cards': {
      const row = frame('cards', { row: true, gap: 16 })
      add(parent, row)
      for (const item of block.items) {
        const card = frame(item.heading, { gap: 8, padY: 20, padX: 20, surface: 'theme/surface-raised', radius: 16 })
        add(row, card)
        add(card, text(item.heading, { font: 'sansMedium', size: 18, slot: 'text' }))
        add(card, text(item.body, { size: 14, slot: 'text-muted' }))
      }
      return row
    }
    case 'footer': {
      const footer = text(block.text, { font: 'mono', size: 12, slot: 'text-muted' })
      footer.name = 'footer'
      return add(parent, footer)
    }
    default:
      problems.push(path + ': unknown block kind ' + block.kind)
      return null
  }
}

/** Children in document order, with the same sibling numbering the spec uses. */
async function children(parent, blocks, prefix) {
  const seen = {}
  for (const block of blocks || []) {
    const base = segment(block)
    seen[base] = (seen[base] || 0) + 1
    const own = seen[base] > 1 ? base + '#' + seen[base] : base
    await render(parent, block, prefix ? prefix + ' > ' + own : own)
  }
}

function segment(block) {
  if (block.kind === 'hero') return 'hero'
  if (block.kind === 'section') return 'section#' + block.id
  if (block.kind === 'row') return block.name
  if (block.kind === 'group') return 'group:' + block.label
  if (block.kind === 'spec') return 'spec:' + block.label
  if (block.kind === 'instance') return block.component
  if (block.kind === 'standin') return 'standin:' + block.name
  if (block.kind === 'snippet') return 'snippet:' + block.caption
  return block.kind
}

/* ---------- assemble ---------- */

// Where the frame lives is answered by its recorded id first, exactly the way
// the token push prefers a recorded variable id over a name: someone dragging
// the frame to another page is a move to follow, not a stray copy to make. If
// the id is gone — a cut and paste mints a new one — fall back to the recorded
// pages, then to the frame's own name.
let previous = FRAME_ID ? await figma.getNodeByIdAsync(FRAME_ID) : null
if (previous && previous.removed) previous = null

let page = previous ? previous.parent : null
if (!page || page.type !== 'PAGE') {
  page = null
  for (const id of PAGE_IDS) {
    const found = await figma.getNodeByIdAsync(id)
    if (found && found.type === 'PAGE' && !found.removed) {
      page = found
      break
    }
  }
}
if (!page) throw new Error('no page found for ' + FRAME_NAME + ': tried ' + PAGE_IDS.join(', ') + '. Update figma/sync.json.')

// The async setter, not the sync assignment: the sync one throws here,
// and it is also what loads the page's contents.
await figma.setCurrentPageAsync(page)

if (!previous) previous = page.children.find((n) => n.name === FRAME_NAME) || null

// Rebuilt rather than patched. The page is generated from the code; what a
// person changed here is what \`pnpm figma:audit\` reports *before* this runs,
// which is the round trip working rather than a merge conflict in a canvas.
// Its position is kept, because where it sits on the canvas is a decision the
// code has no opinion about.
const previousModes = previous ? { ...previous.explicitVariableModes } : {}

// Rebuilt *in place*. The obvious implementation removes the old frame and
// appends a new one, and it is wrong: someone may have turned this frame into a
// component — ours is one — and deleting it detaches every instance of it. So
// the node keeps its identity and only its children are replaced. Its position,
// its mode and its component-ness are Figma's business, not this script's.
const root = previous || frame(FRAME_NAME, { gap: 56, padY: 64, padX: 64, surface: 'theme/page', width: WIDTH })
if (previous) {
  for (const child of [...previous.children]) child.remove()
  frame(FRAME_NAME, { gap: 56, padY: 64, padX: 64, surface: 'theme/page', width: WIDTH }, previous)
} else {
  page.appendChild(root)
}

// Which mode the frame is *viewed* in is a Figma decision, like where it sits
// on the canvas: the tokens define both modes and the code has no opinion about
// which one someone is looking at. So an existing frame's mode is carried over,
// and only a brand new frame is pinned — to dark, the ground the book was
// designed on.
const themeCollection = (await figma.variables.getLocalVariableCollectionsAsync()).find((c) => c.name === 'theme')
if (themeCollection) {
  const inherited = previousModes[themeCollection.id]
  const dark = themeCollection.modes.find((m) => m.name === 'Dark')
  const modeId = inherited || (dark && dark.modeId)
  if (modeId) root.setExplicitVariableModeForCollection(themeCollection, modeId)
}

await children(root, SPEC.blocks, '')

figma.currentPage.selection = [root]

return {
  pageId: page.id,
  frameId: root.id,
  frameType: root.type,
  instances: placed,
  counts: { instances: placed.length, blocks: SPEC.blocks.length },
  missingFonts,
  missingVariables: [...missingVariables],
  problems,
}
`
}

/**
 * The read-back program: what the page *is* now, in the shape the audit reads.
 *
 * It walks the frame by name, so the addresses it reports are the same ones the
 * spec generates — a block that moved is reported where a person can find it.
 */
function snapshotScript(where: Target) {
	return `// generated by scripts/figma-page.ts — do not edit
const FRAME_ID = ${JSON.stringify(where.frameId ?? null)}
const PAGE_IDS = ${JSON.stringify(where.pageIds)}
const FRAME_NAME = ${JSON.stringify(FRAME_NAME)}

// Same resolution as the push, for the same reason: read back whatever the
// frame is now, wherever someone has moved it to.
let root = FRAME_ID ? await figma.getNodeByIdAsync(FRAME_ID) : null
if (root && root.removed) root = null

let page = root ? root.parent : null
if (!page || page.type !== 'PAGE') {
  page = null
  for (const id of PAGE_IDS) {
    const found = await figma.getNodeByIdAsync(id)
    if (found && found.type === 'PAGE' && !found.removed) {
      page = found
      break
    }
  }
}
if (!page) return { page: null }

// Switching to the page is what loads its contents; loadAllPagesAsync is not
// available here.
await figma.setCurrentPageAsync(page)

if (!root) root = page.children.find((n) => n.name === FRAME_NAME) || null
if (!root) return { page: { frame: null, items: [] } }

const items = []

// Blocks the generator draws as one unit: a swatch grid's cells and a stand-in's
// label have no counterpart in the page, so walking into them would report a few
// hundred nodes the audit is required to ignore — and overflow the read.
const OPAQUE = /^(standin:|snippet:|swatches$|ramps$|typeSpecimens$|cards$)/
/** A spec card's own chrome, not an addressed block. */
const CHROME = /^(head|tag)$/
/** Text the generator named after a block, and therefore addressed like one. */
const NAMED_TEXT = /^(note|footer)$/

// Instances report the component they came from; a frame whose name matches a
// component is how a detached instance looks from here, and saying so is the
// point — that is the drift a name-only comparison would call "fine".
async function visit(node, prefix) {
  const seen = {}
  for (const child of node.children || []) {
    const base = child.name
    seen[base] = (seen[base] || 0) + 1
    const path = (prefix ? prefix + ' > ' : '') + (seen[base] > 1 ? base + '#' + seen[base] : base)

    if (child.type === 'INSTANCE') {
      const main = await child.getMainComponentAsync()
      const set = main && main.parent && main.parent.type === 'COMPONENT_SET' ? main.parent : null
      const props = {}
      for (const [key, value] of Object.entries(child.componentProperties || {})) {
        if (value.type === 'VARIANT') props[key] = value.value
      }
      items.push({ path, kind: 'instance', component: set ? set.name : main ? main.name : null, props })
      continue
    }

    // Prose is counted for the sibling numbering but not reported: the audit
    // compares composition, not typography, and a page's worth of copy would
    // bury the findings that matter. A note is the exception — it is a block.
    if (CHROME.test(child.name)) continue
    if (child.type !== 'TEXT') items.push({ path, kind: 'frame' })
    else if (NAMED_TEXT.test(child.name)) items.push({ path, kind: 'text' })
    if (child.children && !OPAQUE.test(child.name)) await visit(child, path)
  }
}

await visit(root, '')

return { page: { frame: root.name, frameId: root.id, pageId: page.id, items } }
`
}

/** Where a previous push left the frame — and where to look if it has moved. */
interface Target {
	frameId?: string
	/** Recorded page first, then the page the components live on. */
	pageIds: string[]
}

async function main() {
	const state = await readState()

	const html = await readFile(resolve(process.cwd(), SOURCE), 'utf8')
	const spec = extractPage(html, { source: SOURCE })

	await writeFile(SPEC_PATH, `${JSON.stringify(spec, null, '\t')}\n`, 'utf8')

	const record = flag('record')
	if (record) {
		const result = JSON.parse(await readFile(resolve(process.cwd(), record), 'utf8')) as {
			pageId: string
			frameId: string
			instances: Array<{ path: string; component: string; id: string }>
			problems?: string[]
		}

		state.pages = {
			...state.pages,
			[SOURCE]: {
				pageId: result.pageId,
				frameId: result.frameId,
				instances: result.instances.map(({ path, component, id }) => ({ path, component, id })),
			},
		}
		await writeState(state)

		console.log(`figma-page: recorded ${result.instances.length} instances -> figma/sync.json`)
		for (const problem of result.problems ?? []) console.log(`  ! ${problem}`)
		return
	}

	/* Only components the contract *and* Figma both know can be instantiated. */
	const components = Object.fromEntries(Object.entries(state.components ?? {}).map(([name, c]) => [name, c.id]))
	const wanted = [...new Set(instancesOf(spec).map((i) => i.component))]
	const unknown = wanted.filter((name) => !components[name])
	if (unknown.length) {
		throw new Error(
			`no Figma component recorded for ${unknown.join(', ')}. ` +
				`Push the component set first, then record it in figma/sync.json.`,
		)
	}

	const recorded = state.pages?.[SOURCE]
	const where: Target = {
		...(recorded?.frameId ? { frameId: recorded.frameId } : {}),
		pageIds: [...new Set([recorded?.pageId, state.pageId].filter(Boolean) as string[])],
	}

	await writeFile(OUT_PATH, pluginScript(spec, components, where), 'utf8')
	if (has('snapshot')) await writeFile(SNAPSHOT_PATH, snapshotScript(where), 'utf8')

	console.log(describe(spec))
	console.log(`  ${paths(spec.blocks).length} addressed blocks`)
	console.log(`\nfigma-page: ${SPEC_PATH.replace(`${process.cwd()}/`, '')} + ${OUT_PATH.replace(`${process.cwd()}/`, '')}`)
	console.log(
		`  file ${state.fileKey}, frame "${FRAME_NAME}" ` +
			(where.frameId ? `(${where.frameId})` : '(new)') +
			` on page ${where.pageIds.join(' or ')}`,
	)
	console.log(`  instantiating: ${wanted.map((name) => `${name} (${components[name]})`).join(', ')}`)
	console.log(`\nRun ${join('dist', 'figma-page.js')} via use_figma, then:`)
	console.log(`  pnpm figma:page --record <result.json>`)
}

await main()
