/**
 * figma-og — puts the OG card templates into the round trip.
 *
 * Same split as `figma-push.ts` and `figma-page.ts`: this file decides *what*
 * Figma should hold and emits a self-contained program that makes it so,
 * `use_figma` runs it, and `--record` folds the returned ids back into
 * `figma/sync.json`. Everything above the transport is tested offline in
 * `figma/og.ts`.
 *
 * What makes this one different is that a card has two halves travelling in
 * opposite directions. The artwork only ever goes *out*: it is a three.js
 * render, Figma cannot produce one, and the push therefore places it as an
 * image and never reads it back. The spec only ever comes *in*: a dozen fields
 * a designer can edit on the card in Figma, which `--pull` reconciles against
 * `og/specs/*.json` exactly the way the token pull reconciles colours.
 *
 * The bytes of the artwork are the one thing this script cannot deliver
 * itself — the plugin sandbox has no network back to this repo, and inlining
 * 2.6 MB of JPEG into the program is not an option — so the image travels
 * through `upload_assets`, addressed to the `art` node id the push hands back.
 * That is why uploading is its own step with its own flag.
 *
 *   pnpm figma:og                    # emit dist/figma-og.{js,json} + a summary
 *   pnpm figma:og --snapshot         # also emit the read-back program
 *   pnpm figma:og --record out.json  # fold the ids in, print the upload plan
 *   pnpm figma:og --uploaded         # stamp the artwork as landed
 *   pnpm figma:og --pull snap.json [--prefer=code|figma] [--apply]
 */
import { createHash } from 'node:crypto'
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'

import { flag, has } from './figma/args.js'
import {
	FIELDS,
	SCOPE,
	applyEdits,
	describe,
	keyOf,
	parseKey,
	renderPlan,
	templatesFrom,
	valuesOf,
	type Field,
	type Template,
} from './figma/og.js'
import { nextBase, reconcile, summarise, type Entry, type Policy } from './figma/reconcile.js'
import { readState, reportPath, syncId, writeState, type SyncState } from './figma/state.js'
import { families } from '../src/pmndrs-design-book.js'

const SPEC_PATH = resolve(process.cwd(), 'dist', 'figma-og.json')
const OUT_PATH = resolve(process.cwd(), 'dist', 'figma-og.js')
const SNAPSHOT_PATH = resolve(process.cwd(), 'dist', 'figma-og-snapshot.js')

/** The frame every template sits in, and the name a re-push finds it by. */
const ROOT_NAME = 'og/templates'

/** Every card is shown this wide, whatever it renders at. */
const ART_WIDTH = 480
const PAD = 20
/** The field-name column, wide enough for `chromaticAberration`'s neighbours. */
const LABEL_WIDTH = 96
/** Cards per row. The grid wraps, so this only decides the frame's width. */
const COLUMNS = 4

/**
 * How many cards one `use_figma` call builds.
 *
 * A card is about thirty nodes, so all fourteen in one program would be four
 * hundred — well past the point where a single plugin run is a good idea. The
 * batches are independent because the push is an upsert: running the same batch
 * twice is a no-op, and a batch that fails changes nothing, since a failed
 * `use_figma` script does not execute at all.
 */
const BATCH = 5

const FACES = {
	sans: { family: families.sans, style: 'Regular' },
	sansMedium: { family: families.sans, style: 'Medium' },
	mono: { family: families.mono, style: 'Regular' },
}

/* ------------------------------------------------------------- the program */

/**
 * The program that runs inside Figma.
 *
 * One rule shapes all of it: a component is **updated in place, never rebuilt**.
 * The demo page can afford to delete its children and draw them again, because
 * everything in it is derived from the spec. A card cannot: its `art` node
 * carries an image that was uploaded separately and is not in this payload, so
 * a node dropped and recreated would come back blank and need every one of the
 * fourteen images sent again. Worse, the cards are components — deleting one
 * detaches every instance of it and voids its Code Connect mapping. So children
 * are matched by name and reused, and only their contents are rewritten.
 */
function pluginScript(templates: Template[], known: Record<string, { id: string }>, where: Target) {
	const payload = templates.map((t) => ({
		key: t.key,
		w: t.width,
		h: t.height,
		kind: t.kind,
		out: t.out,
		fields: t.fields,
	}))

	return `// generated by scripts/figma-og.ts — do not edit
const TEMPLATES = ${JSON.stringify(payload)}
const KNOWN = ${JSON.stringify(known)}
const PAGE_ID = ${JSON.stringify(where.pageId)}
const ROOT_ID = ${JSON.stringify(where.rootId ?? null)}
const ROOT_NAME = ${JSON.stringify(ROOT_NAME)}
const FIELDS = ${JSON.stringify(FIELDS)}
const ART_WIDTH = ${ART_WIDTH}
const PAD = ${PAD}
const LABEL_WIDTH = ${LABEL_WIDTH}
const CARD_WIDTH = ART_WIDTH + PAD * 2
const VALUE_WIDTH = ART_WIDTH - LABEL_WIDTH - 10
const COLUMNS = ${COLUMNS}
/** Every card the demo renders, so a batch can still tell what is left over. */
const ALL_NAMES = ${JSON.stringify(where.allNames)}

/* ---------- fonts ---------- */

const WANTED = ${JSON.stringify(FACES)}
const FALLBACK = { family: 'Inter', style: 'Regular' }
const FONTS = {}
const missingFonts = []
for (const [key, font] of Object.entries(WANTED)) {
  try {
    await figma.loadFontAsync(font)
    FONTS[key] = font
  } catch {
    missingFonts.push(font.family + ' ' + font.style)
    FONTS[key] = FALLBACK
  }
}
await figma.loadFontAsync(FALLBACK)

/* ---------- variables ---------- */

const allVariables = await figma.variables.getLocalVariablesAsync()
// Both keyings — see the note in scripts/figma-page.ts. A variable names its
// collection as a prefix, or wears it by living in one; this file is the
// second kind, and a lookup that only knew the first found nothing at all.
const collectionNames = new Map(
  (await figma.variables.getLocalVariableCollectionsAsync()).map((c) => [c.id, c.name]),
)
const variableByName = new Map()
for (const v of allVariables) {
  if (!variableByName.has(v.name)) variableByName.set(v.name, v)
  variableByName.set((collectionNames.get(v.variableCollectionId) || '') + '/' + v.name, v)
}
const missingVariables = new Set()
const problems = []

function variable(name) {
  const found = variableByName.get(name)
  if (!found) missingVariables.add(name)
  return found || null
}

function fill(node, name) {
  const v = variable(name)
  if (!v) return node
  node.fills = [figma.variables.setBoundVariableForPaint(figma.util.solidPaint('#808080'), 'color', v)]
  return node
}

function stroke(node, name) {
  const v = variable(name)
  if (!v) return node
  node.strokes = [figma.variables.setBoundVariableForPaint(figma.util.solidPaint('#808080'), 'color', v)]
  node.strokeWeight = 1
  return node
}

/* ---------- primitives ---------- */

/**
 * A child of \`parent\` with this name, reused if it is already there.
 *
 * The whole update-in-place strategy rests on this: \`art\` comes back as the
 * same node on every push, so the image someone uploaded onto it survives.
 */
function child(parent, name, type) {
  const found = parent.children.find((n) => n.name === name)
  if (found) {
    if (found.type === type) return found
    // A node of the wrong type under a name we own is someone else's edit.
    // Removing it silently would delete their work, so say so and move on.
    problems.push(parent.name + ' > ' + name + ' is a ' + found.type + ', expected ' + type)
    return null
  }
  const node = type === 'TEXT' ? figma.createText() : figma.createFrame()
  node.name = name
  parent.appendChild(node)
  return node
}

function layout(node, opts) {
  const o = opts || {}
  // Before the sizing modes, never after: resize() resets them to FIXED, so a
  // frame given its width last would stop hugging its own content.
  if (o.width != null) node.resize(o.width, Math.max(1, node.height))
  node.layoutMode = o.row ? 'HORIZONTAL' : 'VERTICAL'
  // Figma names the axes after the layout direction, not after the screen: in a
  // row the *primary* axis is the width, in a column it is the height. So a
  // fixed width is primaryAxisSizingMode in a row and counterAxisSizingMode in
  // a column, and getting it backwards pins the height instead — which is how
  // the first push produced a wrapping grid 100px tall with every card clipped.
  const width = o.width != null ? 'FIXED' : 'AUTO'
  node.primaryAxisSizingMode = o.row ? width : 'AUTO'
  node.counterAxisSizingMode = o.row ? 'AUTO' : width
  node.itemSpacing = o.gap == null ? 12 : o.gap
  node.paddingTop = node.paddingBottom = o.padY == null ? 0 : o.padY
  node.paddingLeft = node.paddingRight = o.padX == null ? 0 : o.padX
  if (o.wrap) {
    node.layoutWrap = 'WRAP'
    node.counterAxisSpacing = o.gap == null ? 12 : o.gap
  }
  if (o.align) node.counterAxisAlignItems = o.align
  if (o.radius != null) node.cornerRadius = o.radius
  if (o.surface) fill(node, o.surface)
  else if (!o.keepFill) node.fills = []
  if (o.line) stroke(node, o.line)
  return node
}

/**
 * Writes text, loading whatever font the node already carries.
 *
 * The order is the same trap \`figma-page.ts\` documents: a text node switched to
 * HEIGHT before it has characters keeps a zero width, lays out one character
 * per line and grows to thousands of pixels. Characters first — while the node
 * still sizes to its content — then measure, and only then let it grow
 * downward. Setting FILL afterwards does not rescue a node that skipped this.
 */
async function write(node, chars, opts) {
  const o = opts || {}
  const font = FONTS[o.font || 'sans']

  // An existing node may be set in something else entirely; load that too or
  // assigning characters throws.
  const current = node.fontName
  if (current === figma.mixed) {
    for (let i = 0; i < node.characters.length; i++) await figma.loadFontAsync(node.getRangeFontName(i, i + 1))
  } else if (current) {
    try { await figma.loadFontAsync(current) } catch {}
  }

  node.fontName = font
  node.fontSize = o.size || 13
  node.lineHeight = { unit: 'PERCENT', value: o.leading || 150 }
  node.textAutoResize = 'WIDTH_AND_HEIGHT'
  // Figma will not hold an empty string, so a blank field is written as a single
  // space. The snapshot reads it back as the empty value it stands for.
  node.characters = chars === '' ? ' ' : chars

  // \`wrap\` caps a measured width; \`width\` pins one. Both have to switch the
  // node to HEIGHT before resizing, or the resize is simply undone.
  if (o.wrap || o.width) {
    const measured = o.width || Math.max(1, Math.min(node.width, o.wrap))
    node.textAutoResize = 'HEIGHT'
    node.resize(measured, node.height)
  }

  fill(node, 'theme/' + (o.slot || 'text-body'))
  return node
}

/** Appends in the given order, which is what actually reorders existing children. */
function order(parent, nodes) {
  for (const node of nodes) if (node && node.parent === parent) parent.appendChild(node)
}

/**
 * Forces a frame's subtree to recompute its resolved variable colours.
 *
 * Figma caches those, and rewriting the paints underneath does not reliably
 * invalidate the cache: the frame renders flat #808080 — the fallback colour
 * carried inside every bound paint — while the API reports the bindings intact
 * and resolves them to the right colour. Toggling an explicit mode on and off
 * makes it recompute, and restores whatever pin it found.
 */
function repaint(node, collection) {
  if (!collection || !collection.modes.length) return
  const pinned = (node.explicitVariableModes || {})[collection.id]
  const other = collection.modes.find((m) => m.modeId !== pinned) || collection.modes[0]
  node.setExplicitVariableModeForCollection(collection, other.modeId)
  if (pinned) node.setExplicitVariableModeForCollection(collection, pinned)
  else node.clearExplicitVariableModeForCollection(collection)
}

/* ---------- the card ---------- */

const results = []

async function card(parent, template) {
  const name = 'og/' + template.key

  let node = KNOWN[template.key] ? await figma.getNodeByIdAsync(KNOWN[template.key].id) : null
  if (node && (node.removed || node.type !== 'COMPONENT')) node = null

  if (!node) {
    // Someone may have cut and pasted the component, which mints a new id.
    const byName = figma.currentPage.findAllWithCriteria({ types: ['COMPONENT'] }).find((c) => c.name === name)
    node = byName || null
  }

  const created = !node
  if (!node) node = figma.createComponent()
  node.name = name

  // Reparented rather than rebuilt: appendChild on a node that already has a
  // parent moves it, so a card that was pushed before keeps its identity — and
  // with it its uploaded artwork, its instances and its Code Connect mapping.
  parent.appendChild(node)

  // A fixed width, so the fields under the artwork wrap at a predictable
  // measure — a hugging card would be as wide as its longest subtitle.
  layout(node, {
    gap: 16, padX: PAD, padY: PAD, radius: 16,
    surface: 'theme/surface', line: 'theme/line-soft', width: CARD_WIDTH,
  })
  node.description =
    'Generated by pnpm figma:og from ' + (template.out || 'og/specs') + '. ' +
    'The artwork is a render — edit the fields, not the image, and run pnpm figma:og --pull.'

  /* The artwork. Sized here; its fill is uploaded separately. */
  const art = child(node, 'art', 'FRAME')
  if (art) {
    const height = Math.round((ART_WIDTH * template.h) / template.w)
    art.resize(ART_WIDTH, height)
    art.cornerRadius = 8
    art.clipsContent = true
    // Only paint a placeholder when there is nothing there yet: an IMAGE fill is
    // the uploaded render, and overwriting it would undo the upload on every push.
    const hasImage = (art.fills || []).some((f) => f.type === 'IMAGE')
    if (!hasImage) fill(art, 'theme/surface-sunken')
    art.layoutSizingHorizontal = 'FIXED'
  }

  /* The caption: what this card is, and what it really renders at. */
  const caption = child(node, 'caption', 'FRAME')
  if (caption) {
    layout(caption, { row: true, gap: 8, align: 'CENTER', wrap: true })
    caption.layoutSizingHorizontal = 'FILL'
    const label = child(caption, 'key', 'TEXT')
    if (label) await write(label, template.key, { font: 'mono', size: 11, slot: 'text-muted' })
    const size = child(caption, 'output', 'TEXT')
    if (size) {
      await write(size, template.w + '×' + template.h + ' · ' + template.kind, {
        font: 'mono', size: 11, slot: 'text-faint',
      })
    }
    order(caption, [label, size])
  }

  /* The fields. These are the round trip: everything else here is a picture. */
  const fields = child(node, 'fields', 'FRAME')
  const rows = []
  if (fields) {
    layout(fields, { gap: 6 })
    fields.layoutSizingHorizontal = 'FILL'

    for (const field of FIELDS) {
      const row = child(fields, 'row:' + field, 'FRAME')
      if (!row) continue
      layout(row, { row: true, gap: 10 })
      row.layoutSizingHorizontal = 'FILL'

      const label = child(row, 'label:' + field, 'TEXT')
      if (label) {
        await write(label, field, { font: 'mono', size: 10, slot: 'text-faint', width: LABEL_WIDTH })
        label.layoutSizingHorizontal = 'FIXED'
      }

      // The one editable thing on the card, and the only node the snapshot reads.
      const value = child(row, 'field:' + field, 'TEXT')
      if (value) {
        await write(value, template.fields[field], { font: 'sans', size: 12, slot: 'text-body', wrap: VALUE_WIDTH })
        value.layoutSizingHorizontal = 'FILL'
      }

      order(row, [label, value])
      rows.push(row)
    }
    order(fields, rows)
  }

  order(node, [art, caption, fields])

  results.push({
    key: template.key,
    id: node.id,
    art: art ? art.id : null,
    created,
  })
  return node
}

/* ---------- assemble ---------- */

const page = await figma.getNodeByIdAsync(PAGE_ID)
if (!page || page.type !== 'PAGE' || page.removed) {
  throw new Error('no page ' + PAGE_ID + ' in this file. Update figma/sync.json.')
}
await figma.setCurrentPageAsync(page)

let root = ROOT_ID ? await figma.getNodeByIdAsync(ROOT_ID) : null
if (root && (root.removed || root.type !== 'FRAME')) root = null
if (!root) root = page.children.find((n) => n.name === ROOT_NAME && n.type === 'FRAME') || null
if (!root) {
  root = figma.createFrame()
  root.name = ROOT_NAME
  page.appendChild(root)
}

layout(root, { gap: 40, padX: 64, padY: 64, surface: 'theme/page' })

// A brand new frame lands on dark, the ground the book was designed on; an
// existing one keeps whichever mode someone is viewing it in. Same rule as the
// demo page: which mode you look at it in is Figma's business, not the code's.
//
// But only when dark is not already what an unpinned frame resolves to. Pinning
// a frame to its collection's *default* mode is redundant, and in this file it
// is also enough to stop the renderer resolving that frame's own bound paints:
// the root came back flat #808080 — the fallback colour inside every bound
// paint — while its children rendered correctly. Clearing the pin fixed it, and
// the demo page's frame, which pins Light, was never affected. So say nothing
// when there is nothing to say.
const themeCollection = (await figma.variables.getLocalVariableCollectionsAsync()).find((c) => c.name === 'theme')
if (themeCollection && !Object.keys(root.explicitVariableModes || {}).includes(themeCollection.id)) {
  const dark = themeCollection.modes.find((m) => m.name === 'Dark')
  if (dark && themeCollection.defaultModeId !== dark.modeId) {
    root.setExplicitVariableModeForCollection(themeCollection, dark.modeId)
  }
}

const heading = child(root, 'heading', 'TEXT')
if (heading) {
  await write(heading, 'OG image templates', { font: 'sansMedium', size: 28, slot: 'text' })
}
const note = child(root, 'note', 'TEXT')
if (note) {
  await write(note, 'Every card that pnpm og:demo renders. The picture is the render itself and cannot be edited here — the fields under it are the spec, and pnpm figma:og --pull carries your edits back to og/specs/*.json.', { size: 13, slot: 'text-muted', wrap: 720 })
}

const grid = child(root, 'cards', 'FRAME')
if (!grid) throw new Error('cards frame is not a frame')
// A wrapping row needs a width to wrap *at*: left to hug, it would lay all
// fourteen cards out in one line seven thousand pixels wide.
layout(grid, { row: true, wrap: true, gap: 24, width: COLUMNS * CARD_WIDTH + (COLUMNS - 1) * 24 })

const placed = []
for (const template of TEMPLATES) placed.push(await card(grid, template))
order(grid, placed)
order(root, [heading, note, grid])

// Anything in the grid that the demo no longer renders. Compared against every
// card rather than this batch's, so a partial run does not report the cards a
// later batch is about to place. Reported, never deleted — a component may
// still have instances, and detaching someone's work is not this script's call.
const stale = grid.children.filter((n) => ALL_NAMES.indexOf(n.name) === -1).map((n) => n.name)

repaint(root, themeCollection)

figma.currentPage.selection = [root]

return {
  pageId: page.id,
  rootId: root.id,
  templates: results,
  stale,
  counts: {
    templates: results.length,
    created: results.filter((r) => r.created).length,
    updated: results.filter((r) => !r.created).length,
  },
  missingFonts,
  missingVariables: [...missingVariables],
  problems,
}
`
}

/**
 * The read-back program: what the fields say in Figma right now.
 *
 * Deliberately narrow. It reads the `field:*` text layers and nothing else,
 * because they are the only things in the card a person can change that this
 * repo can act on. Everything else on the canvas — the artwork, the caption,
 * the layout — is generated, and reporting drift in it would be reporting that
 * the last push ran.
 */
function snapshotScript(where: Target) {
	return `// generated by scripts/figma-og.ts — do not edit
const PAGE_ID = ${JSON.stringify(where.pageId)}
const ROOT_ID = ${JSON.stringify(where.rootId ?? null)}
const ROOT_NAME = ${JSON.stringify(ROOT_NAME)}
const KNOWN = ${JSON.stringify(where.known)}

const page = await figma.getNodeByIdAsync(PAGE_ID)
if (!page || page.type !== 'PAGE') return { values: {}, missing: ['page ' + PAGE_ID] }
await figma.setCurrentPageAsync(page)

let root = ROOT_ID ? await figma.getNodeByIdAsync(ROOT_ID) : null
if (root && root.removed) root = null
if (!root) root = page.children.find((n) => n.name === ROOT_NAME) || null

const values = {}
const missing = []
const detached = []

// By recorded id first, then by name — the same resolution the push uses, so a
// component someone moved off the frame is still found and still compared.
for (const [key, recorded] of Object.entries(KNOWN)) {
  let node = await figma.getNodeByIdAsync(recorded.id)
  if (node && node.removed) node = null
  if (!node) {
    node = figma.currentPage.findAllWithCriteria({ types: ['COMPONENT'] }).find((c) => c.name === 'og/' + key) || null
    if (node) detached.push(key + ' moved to ' + node.id)
  }
  if (!node) {
    missing.push(key)
    continue
  }

  for (const text of node.findAllWithCriteria({ types: ['TEXT'] })) {
    if (text.name.indexOf('field:') !== 0) continue
    // A single space is how the push writes an empty value, because Figma will
    // not accept an empty string. Read it back as the empty value it stands for.
    const chars = text.characters === ' ' ? '' : text.characters
    values['og.' + key + '.' + text.name.slice('field:'.length)] = chars
  }
}

return { values, missing, detached, root: root ? root.id : null }
`
}

/* ---------------------------------------------------------------- the CLI */

interface Target {
	pageId: string
	rootId?: string
	known: Record<string, { id: string }>
	/** Every card's component name, so a batch can still spot a stale one. */
	allNames: string[]
}

/** What a previous push left behind, per template. */
interface OgRecord {
	id: string
	art?: string
	/** sha256 of the artwork file at the time it was uploaded. */
	sha?: string
}

interface OgState {
	pageId: string
	rootId?: string
	templates: Record<string, OgRecord>
}

/** `figma/sync.json` gains one section; the rest of the round trip is untouched. */
type StateWithOg = SyncState & { og?: OgState }

const sha256 = (bytes: Buffer) => createHash('sha256').update(bytes).digest('hex')

async function readTemplates() {
	const og = resolve(process.cwd(), 'og')
	const plan = renderPlan(await readFile(join(og, 'package.json'), 'utf8'))

	const names = await readdir(join(og, 'specs'))
	const specFiles = Object.fromEntries(
		await Promise.all(
			names
				.filter((name) => name.endsWith('.json'))
				.map(async (name) => [`specs/${name}`, await readFile(join(og, 'specs', name), 'utf8')] as const),
		),
	)

	return templatesFrom(plan, specFiles)
}

/** The artwork whose bytes differ from what Figma was last given. */
async function uploadPlan(templates: Template[], og: OgState) {
	const out: Array<{ key: string; art: string; node: string; sha: string; bytes: number }> = []

	for (const template of templates) {
		if (!template.art) continue
		const record = og.templates[template.key]
		if (!record?.art) continue

		const bytes = await readFile(resolve(process.cwd(), template.art))
		const sha = sha256(bytes)
		if (record.sha === sha) continue
		out.push({ key: template.key, art: template.art, node: record.art, sha, bytes: bytes.length })
	}

	return out
}

function ogOf(state: StateWithOg, pageId: string): OgState {
	return state.og ?? { pageId, templates: {} }
}

/* ------------------------------------------------------------------ report */

function renderReport(id: string, entries: Entry[], policy: Policy, applied: boolean, templates: Template[]) {
	const counts = summarise(entries)
	const where = new Map(templates.map((t) => [t.key, t]))

	const lines = [
		`# OG sync ${id}`,
		'',
		`Direction: Figma -> code. ${entries.length} entr${entries.length === 1 ? 'y' : 'ies'}.`,
		'',
		'| outcome | count |',
		'| --- | --- |',
		...Object.entries(counts).map(([k, n]) => `| ${k} | ${n} |`),
		'',
	]

	const named = (key: string) => {
		const parsed = parseKey(key)
		if (!parsed) return `\`${key}\``
		const template = where.get(parsed.template)
		return `\`${parsed.template}\` · **${parsed.field}**${template ? ` (${template.source})` : ''}`
	}

	const section = (title: string, kinds: string[], body: (e: Entry) => string) => {
		const hits = entries.filter((e) => kinds.includes(e.verdict.kind))
		if (!hits.length) return
		lines.push(`## ${title}`, '')
		for (const e of hits) lines.push(`- ${body(e)}`)
		lines.push('')
	}

	section('Pulled from Figma', ['pull'], (e) => {
		const v = e.verdict as { kind: 'pull'; value: string }
		return `${named(e.key)} -> \`${v.value}\``
	})
	section('Resolved by policy', ['resolved'], (e) => {
		const v = e.verdict as { kind: 'resolved'; winner: string; ours: string; theirs: string }
		return `${named(e.key)}: code \`${v.ours}\` vs Figma \`${v.theirs}\` — **${v.winner}** won`
	})
	section('Conflicts — need a decision', ['conflict'], (e) => {
		const v = e.verdict as { kind: 'conflict'; ours: string; theirs: string }
		return `${named(e.key)}: code \`${v.ours}\` vs Figma \`${v.theirs}\``
	})
	section('Only in the specs', ['create'], (e) => `${named(e.key)} — push to create it`)
	section('Only in Figma', ['orphan'], (e) => `${named(e.key)} — no card in the demo renders this`)

	lines.push(
		'',
		'The artwork is not compared: it is a render, and Figma has no way to produce one.',
		'Re-render with `pnpm og:demo`, then `pnpm figma:og` and upload the changed images.',
		'',
		`Scope policy: ${JSON.stringify(policy.override ?? policy.prefer[SCOPE] ?? 'ask')}.`,
		applied ? 'Edits were applied to `og/specs/`.' : 'No files were changed. Re-run with `--apply` to write them.',
		'',
	)
	return lines.join('\n')
}

/** Groups the settled Figma-side edits by the file they have to be written to. */
function editsByFile(entries: Entry[], templates: Template[]) {
	const where = new Map(templates.map((t) => [t.key, t]))
	const files = new Map<string, { card: number | null; edits: Array<{ field: Field; value: string }> }>()

	for (const entry of entries) {
		const value =
			entry.verdict.kind === 'pull'
				? entry.verdict.value
				: entry.verdict.kind === 'resolved' && entry.verdict.winner === 'figma'
					? entry.verdict.value
					: null
		if (value === null) continue

		const parsed = parseKey(entry.key)
		if (!parsed) continue
		const template = where.get(parsed.template)
		if (!template) continue

		/* Keyed by file *and* card: two cards in one manifest are two targets. */
		const id = `${template.source}#${template.card}`
		const bucket = files.get(id) ?? { card: template.card, edits: [] }
		bucket.edits.push({ field: parsed.field, value })
		files.set(id, bucket)
	}

	return [...files].map(([id, bucket]) => ({ source: id.split('#')[0] as string, ...bucket }))
}

/* -------------------------------------------------------------------- main */

async function main() {
	const state = (await readState()) as StateWithOg
	const templates = await readTemplates()

	/* Recording the result of an executed push. */
	const record = flag('record')
	if (record) {
		interface PushResult {
			pageId: string
			rootId: string
			templates: Array<{ key: string; id: string; art: string | null }>
			stale?: string[]
			problems?: string[]
			missingVariables?: string[]
		}

		/* One file per batch, so several are the normal case. */
		const results = (await Promise.all(
			record
				.split(',')
				.map(async (path) => JSON.parse(await readFile(resolve(process.cwd(), path.trim()), 'utf8')) as PushResult),
		)) as PushResult[]

		const last = results[results.length - 1] as PushResult
		const og = ogOf(state, last.pageId)
		og.pageId = last.pageId
		og.rootId = last.rootId

		let recorded = 0
		for (const result of results) {
			for (const { key, id, art } of result.templates) {
				/* The sha is deliberately carried over, not stamped: the push moved no
				   image bytes, so whatever Figma is showing is still the last upload. */
				og.templates[key] = { ...og.templates[key], id, ...(art ? { art } : {}) }
				recorded += 1
			}
		}
		state.og = og
		state.prefer = { [SCOPE]: 'ask', ...state.prefer }

		/*
		 * The base advances here, and it has to.
		 *
		 * A push makes both sides agree, so the values it just wrote are the last
		 * agreed state. Leaving the base empty would not merely lose information —
		 * `reconcile` treats a missing base as "cannot tell who moved", so the very
		 * first real edit a designer made in Figma would come back as a *conflict*
		 * needing a human, rather than as the pull it plainly is.
		 */
		const pushed = valuesOf(templates.filter((t) => og.templates[t.key]))
		const entries: Entry[] = Object.entries(pushed).map(([key, value]) => ({
			key,
			verdict: { kind: 'push', value },
		}))
		state.lastSync = {
			syncId: syncId(new Date()),
			at: new Date().toISOString(),
			values: nextBase(state.lastSync?.values ?? {}, entries),
		}

		await writeState(state)

		console.log(`figma-og: recorded ${recorded} templates -> figma/sync.json`)
		console.log(`  base advanced with ${entries.length} field values`)
		for (const result of results) {
			for (const problem of result.problems ?? []) console.log(`  ! ${problem}`)
			for (const name of result.stale ?? []) console.log(`  ! ${name} is on the page but no longer in the demo`)
			for (const name of result.missingVariables ?? []) console.log(`  ! no variable named ${name}`)
		}

		const plan = await uploadPlan(templates, og)
		if (!plan.length) {
			console.log('\nEvery card already has its current render. Nothing to upload.')
			return
		}
		console.log(`\nUpload ${plan.length} image${plan.length === 1 ? '' : 's'} with upload_assets:`)
		for (const item of plan) console.log(`  ${item.art}  ->  node ${item.node}  (${Math.round(item.bytes / 1024)} KB)`)
		console.log('\nThen: pnpm figma:og --uploaded')
		return
	}

	/* Stamping the artwork as landed, after the uploads have gone through. */
	if (has('uploaded')) {
		const og = state.og
		if (!og) throw new Error('nothing has been pushed yet — run pnpm figma:og and record the result first.')

		const only = flag('only')?.split(',')
		const plan = (await uploadPlan(templates, og)).filter((item) => !only || only.includes(item.key))
		for (const item of plan) {
			/* Only ever reached for a template `uploadPlan` found a record for. */
			const record = og.templates[item.key]
			if (record) og.templates[item.key] = { ...record, sha: item.sha }
		}
		state.og = og
		await writeState(state)

		console.log(`figma-og: stamped ${plan.length} image${plan.length === 1 ? '' : 's'} as uploaded`)
		for (const item of plan) console.log(`  ${item.key} <- ${item.art}`)
		return
	}

	/* Reconciling a snapshot back into the specs. */
	const pull = flag('pull')
	if (pull) {
		const snapshot = JSON.parse(await readFile(resolve(process.cwd(), pull), 'utf8')) as {
			values: Record<string, string>
			missing?: string[]
			detached?: string[]
		}

		const override = flag('prefer') as 'code' | 'figma' | undefined
		if (override && override !== 'code' && override !== 'figma') {
			throw new Error(`--prefer must be code or figma, received "${override}"`)
		}

		const policy: Policy = {
			prefer: state.prefer,
			derived: state.derived,
			...(override ? { override } : {}),
		}

		const entries = reconcile(state.lastSync?.values ?? {}, valuesOf(templates), snapshot.values, policy)
		const id = syncId(new Date())
		const apply = has('apply')

		const report = renderReport(id, entries, policy, apply, templates)
		const out = reportPath(id)
		await mkdir(dirname(out), { recursive: true })
		await writeFile(out, report, 'utf8')

		if (apply) {
			for (const file of editsByFile(entries, templates)) {
				const path = resolve(process.cwd(), file.source)
				await writeFile(path, applyEdits(await readFile(path, 'utf8'), file.edits, file.card), 'utf8')
				console.log(`  wrote ${file.edits.length} field(s) -> ${file.source}`)
			}

			state.lastSync = {
				syncId: id,
				at: new Date().toISOString(),
				values: nextBase(state.lastSync?.values ?? {}, entries),
			}
			await writeState(state)
		}

		const counts = summarise(entries)
		console.log(`figma-og: ${entries.length} entries -> ${out}`)
		for (const [kind, n] of Object.entries(counts)) console.log(`  ${kind}: ${n}`)
		if (!entries.length) console.log('  no drift')
		for (const key of snapshot.missing ?? []) console.log(`  ! ${key} is recorded but not in the file`)
		for (const note of snapshot.detached ?? []) console.log(`  ! ${note}`)
		if (!apply && entries.length) console.log('\nDry run. Re-run with --apply to write the edits and advance the base.')

		if (entries.some((e) => e.verdict.kind === 'conflict')) process.exitCode = 1
		return
	}

	/* Emitting the push. */
	const og = state.og
	const where: Target = {
		pageId: og?.pageId ?? flag('page') ?? state.pageId,
		...(og?.rootId ? { rootId: og.rootId } : {}),
		known: Object.fromEntries(Object.entries(og?.templates ?? {}).map(([key, r]) => [key, { id: r.id }])),
		allNames: templates.map((t) => `og/${t.key}`),
	}

	await mkdir(dirname(OUT_PATH), { recursive: true })
	await writeFile(SPEC_PATH, `${JSON.stringify({ templates }, null, '\t')}\n`, 'utf8')

	/* One program per batch. They are independent upserts, so they can be run in
	   any order and re-run at will; the cards end up in plan order because each
	   batch appends its own to the end of the grid. */
	const batches: Template[][] = []
	for (let i = 0; i < templates.length; i += BATCH) batches.push(templates.slice(i, i + BATCH))

	const paths = await Promise.all(
		batches.map(async (batch, i) => {
			const path = OUT_PATH.replace(/\.js$/, `.${i + 1}.js`)
			await writeFile(path, pluginScript(batch, where.known, where), 'utf8')
			return { path: path.replace(`${process.cwd()}/`, ''), keys: batch.map((t) => t.key) }
		}),
	)

	if (has('snapshot')) await writeFile(SNAPSHOT_PATH, snapshotScript(where), 'utf8')

	const missingArt = templates.filter((t) => !t.art)
	if (missingArt.length) {
		console.log(`! ${missingArt.length} template(s) have no render on disk: ${missingArt.map((t) => t.key).join(', ')}`)
		console.log('  Run `pnpm og:demo` first, or Figma gets an empty box.\n')
	}

	console.log(describe(templates))
	console.log(`  ${templates.length * FIELDS.length} syncable fields`)
	console.log(`\nfigma-og: ${SPEC_PATH.replace(`${process.cwd()}/`, '')}`)
	console.log(`  file ${state.fileKey}, page ${where.pageId}, frame "${ROOT_NAME}" ${where.rootId ?? '(new)'}`)
	console.log(`  ${Object.keys(where.known).length} already have recorded ids; the rest will be created`)
	console.log(`\nRun each of these via use_figma, in order:`)
	for (const { path, keys } of paths) console.log(`  ${path}  — ${keys.join(', ')}`)
	console.log(`\nThen: pnpm figma:og --record <result1.json,result2.json,…>`)
}

await main()
