/**
 * figma-template — puts the card's *layout* into the round trip.
 *
 * `figma-og.ts` sends fourteen cards and brings back what they say.  This sends
 * one frame and brings back where they say it: drag the message block in Figma,
 * pull, and `og/layout/card.json` moves — so the next render of every card
 * moves with it.
 *
 * The template is drawn at the reference box the layout is authored against, so
 * Figma's inspector and the JSON hold the same numbers. It carries the
 * reference card's own render as a backdrop, because type is only judgeable
 * over the artwork it has to stay legible on — and that artwork is the one
 * thing in this whole system Figma cannot produce.
 *
 *   pnpm figma:template                  # dist/figma-template.js + a summary
 *   pnpm figma:template --snapshot       # also the read-back program
 *   pnpm figma:template --record out.json
 *   pnpm figma:template --pull snap.json [--prefer=code|figma] [--apply]
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'

import { flag, has } from './figma/args.js'
import { nextBase, reconcile, summarise, type Entry, type Policy } from './figma/reconcile.js'
import { readState, reportPath, syncId, writeState, type SyncState } from './figma/state.js'
import { SCOPE, applyEdits, describe, flatten, isGeometry, boxOf, type Values } from './figma/template.js'
import { families } from '../src/pmndrs-design-book.js'

const LAYOUT_PATH = resolve(process.cwd(), 'og', 'layout', 'card.json')
const OUT_PATH = resolve(process.cwd(), 'dist', 'figma-template.js')
const SNAPSHOT_PATH = resolve(process.cwd(), 'dist', 'figma-template-snapshot.js')

const FRAME_NAME = 'og/template'

/**
 * The card the template is drawn with.
 *
 * Its render is the backdrop and its copy fills the type, so the frame is a
 * real card rather than a diagram of one — the designer is looking at the exact
 * thing the renderer produces, at the exact size it produces it.
 */
const SAMPLE = {
	art: 'demo/og/template-plate.jpg',
	wordmark: 'pmndrs',
	chip: 'github.com/pmndrs/react-three-fiber',
	eyebrow: 'pmndrs',
	title: 'React Three Fiber',
	/* `wordmark` defaults to the title behind a scene, so the template shows it
	   saying the same thing the card does. */
	wordmark3d: 'React Three Fiber',
	subtitle: 'A React renderer for three.js. Build your scene declaratively, with re-usable components.',
}

const FACES = {
	serif: { family: families.serif, style: 'Regular' },
	sans: { family: families.sans, style: 'Regular' },
	mono: { family: families.mono, style: 'Regular' },
}

interface Layout {
	reference: { width: number; height: number }
	blocks: Record<string, { anchor: string; offset: { x: number; y: number }; measure: number | null; direction: string; gap: number; align: string }>
	type: Record<string, Record<string, unknown>>
	marks: Record<string, Record<string, number>>
}

/* ------------------------------------------------------------- the program */

/**
 * The program that draws the template.
 *
 * Unlike the card push this one *does* rebuild its contents: the template holds
 * nothing that was uploaded separately except the backdrop, which is matched by
 * name and kept. Everything else is a faithful drawing of the JSON, and
 * redrawing it is the cheapest way to guarantee it stays one.
 */
function pluginScript(layout: Layout, fields: Values, where: Target) {
	/* Each block's children, mirroring Typography.tsx's arrangement. The order
	   is the render order, so the frame reads top-to-bottom like the card. */
	const contents = {
		brand: [
			{ kind: 'mark', name: 'dot' },
			{ kind: 'text', name: 'wordmark', text: SAMPLE.wordmark },
		],
		meta: [{ kind: 'chip', name: 'chip', text: SAMPLE.chip }],
		message: [
			{ kind: 'mark', name: 'rule' },
			{ kind: 'text', name: 'eyebrow', text: SAMPLE.eyebrow },
			{ kind: 'text', name: 'title', text: SAMPLE.title },
			{ kind: 'text', name: 'subtitle', text: SAMPLE.subtitle },
		],
		/* The type set inside the 3D scene. It is drawn here in screen space,
		   which is the space the layout authors it in — the renderer converts to
		   world units with the camera actually rendering the card. */
		scene: [{ kind: 'text', name: 'scene', text: SAMPLE.wordmark3d }],
	}

	return `// generated by scripts/figma-template.ts — do not edit
const LAYOUT = ${JSON.stringify(layout)}
const CONTENTS = ${JSON.stringify(contents)}
const FIELDS = ${JSON.stringify(Object.entries(fields).map(([key, value]) => ({ key, value })))}
const FACES = ${JSON.stringify(FACES)}
const PAGE_ID = ${JSON.stringify(where.pageId)}
const FRAME_ID = ${JSON.stringify(where.frameId ?? null)}
const FRAME_NAME = ${JSON.stringify(FRAME_NAME)}
const REF = LAYOUT.reference

/* ---------- fonts ---------- */

const FALLBACK = { family: 'Inter', style: 'Regular' }
const FONTS = {}
const missingFonts = []
for (const [key, font] of Object.entries(FACES)) {
  try { await figma.loadFontAsync(font); FONTS[key] = font }
  catch { missingFonts.push(font.family + ' ' + font.style); FONTS[key] = FALLBACK }
}
await figma.loadFontAsync(FALLBACK)

/* ---------- variables ---------- */

const allVariables = await figma.variables.getLocalVariablesAsync()
// Both keyings — see the note in scripts/figma-page.ts. A variable names its
// collection as a prefix, or wears it by living in one; this file is the
// second kind, and a lookup that only knew the first found nothing at all.
const collectionNames = new Map(
  (await figma.variables.getLocalVariableCollectionsAsync()).map((c) => [c.id, c.name]),
)
const variableByName = new Map()
for (const v of allVariables) {
  if (!variableByName.has(v.name)) variableByName.set(v.name, v)
  variableByName.set((collectionNames.get(v.variableCollectionId) || '') + '/' + v.name, v)
}
const missingVariables = new Set()
const problems = []

function paint(node, name, prop) {
  const v = variableByName.get(name)
  if (!v) { missingVariables.add(name); return node }
  const bound = figma.variables.setBoundVariableForPaint(figma.util.solidPaint('#808080'), 'color', v)
  if (prop === 'stroke') node.strokes = [bound]
  else node.fills = [bound]
  return node
}

/**
 * The palette entry a layout \`ink\` names, as a Figma variable.
 *
 * The card renders these from the resolved palette, which is per-accent; the
 * template can only show one, so it shows the reference card's — teal is not a
 * layout decision and nothing here reads the colour back.
 */
const INK = {
  ink: 'theme/text',
  inkMuted: 'theme/text-muted',
  accent: 'brand/purple',
  ground: 'theme/page',
}

/* ---------- primitives ---------- */

function child(parent, name, type) {
  const found = parent.children.find((n) => n.name === name)
  if (found && found.type === type) return found
  if (found) found.remove()
  const node =
    type === 'TEXT' ? figma.createText() :
    type === 'ELLIPSE' ? figma.createEllipse() :
    type === 'RECTANGLE' ? figma.createRectangle() : figma.createFrame()
  node.name = name
  parent.appendChild(node)
  return node
}

const JUSTIFY = { left: 'MIN', center: 'CENTER', right: 'MAX' }

/**
 * Forces a frame's subtree to recompute its resolved variable colours.
 *
 * Figma caches those, and rewriting the paints underneath does not reliably
 * invalidate the cache: the frame renders flat #808080 — the fallback colour
 * carried inside every bound paint — while the API reports the bindings intact
 * and resolves them to the right colour. Toggling an explicit mode on and off
 * makes it recompute. It costs nothing, it restores any pin it found, and it is
 * the difference between a template a designer can work in and one that looks
 * broken the moment it is pushed a second time.
 */
function repaint(node, collection) {
  if (!collection || !collection.modes.length) return
  const pinned = (node.explicitVariableModes || {})[collection.id]
  const other = collection.modes.find((m) => m.modeId !== pinned) || collection.modes[0]
  node.setExplicitVariableModeForCollection(collection, other.modeId)
  if (pinned) node.setExplicitVariableModeForCollection(collection, pinned)
  else node.clearExplicitVariableModeForCollection(collection)
}

/** Sets the type styles the layout declares, in the order Figma needs them. */
async function style(node, spec) {
  node.fontName = FONTS[spec.font]
  node.fontSize = spec.size
  // em is a fraction of the font size, which is exactly what Figma's PERCENT
  // letter-spacing means — so this survives a size change on either side.
  node.letterSpacing = spec.tracking == null
    ? { unit: 'PERCENT', value: 0 }
    : { unit: 'PERCENT', value: spec.tracking * 100 }
  node.lineHeight = spec.leading == null
    ? { unit: 'AUTO' }
    : { unit: 'PERCENT', value: spec.leading * 100 }
  node.textCase = spec.case === 'upper' ? 'UPPER' : 'ORIGINAL'
  // Set on the node rather than inside the paint, so a designer changes it where
  // they would expect to and the read-back finds it in the same place.
  node.opacity = spec.opacity == null ? 1 : spec.opacity
  paint(node, INK[spec.ink] || 'theme/text')
}

/* ---------- the frame ---------- */

const page = await figma.getNodeByIdAsync(PAGE_ID)
if (!page || page.type !== 'PAGE') throw new Error('no page ' + PAGE_ID + ' in this file.')
await figma.setCurrentPageAsync(page)

let frame = FRAME_ID ? await figma.getNodeByIdAsync(FRAME_ID) : null
if (frame && (frame.removed || frame.type !== 'FRAME')) frame = null
if (!frame) frame = page.children.find((n) => n.name === FRAME_NAME && n.type === 'FRAME') || null

const created = !frame
if (!frame) {
  frame = figma.createFrame()
  frame.name = FRAME_NAME
  page.appendChild(frame)
  // Clear of whatever else is on the page, rather than on top of it at (0,0).
  const others = page.children.filter((n) => n !== frame)
  frame.x = others.length ? Math.max(...others.map((n) => n.x + n.width)) + 160 : 0
  frame.y = others.length ? Math.min(...others.map((n) => n.y)) : 0
}

// Never auto-layout: the blocks are placed by their anchors, and an auto-layout
// parent would take that decision away from the designer the moment they drag.
frame.layoutMode = 'NONE'
frame.resize(REF.width, REF.height)
frame.clipsContent = true

/* The backdrop — matched by name and left alone, because its image was
   uploaded separately and is not in this payload. */
const art = child(frame, 'art', 'RECTANGLE')
art.x = 0
art.y = 0
art.resize(REF.width, REF.height)
if (!(art.fills || []).some((f) => f.type === 'IMAGE')) paint(art, 'theme/page')

/* ---------- the blocks ---------- */

const placed = []

for (const [name, block] of Object.entries(LAYOUT.blocks)) {
  const node = child(frame, 'block:' + name, 'FRAME')
  node.layoutMode = block.direction === 'row' ? 'HORIZONTAL' : 'VERTICAL'
  // In a row the primary axis is the width; in a column it is the height. A
  // measure therefore pins a different axis in each, and crossing them is what
  // pins the height and clips the content instead.
  const measured = block.measure != null
  if (measured) node.resize(block.measure, Math.max(1, node.height))
  node.primaryAxisSizingMode = block.direction === 'row' ? (measured ? 'FIXED' : 'AUTO') : 'AUTO'
  node.counterAxisSizingMode = block.direction === 'row' ? 'AUTO' : (measured ? 'FIXED' : 'AUTO')
  node.itemSpacing = block.gap
  node.fills = []
  node.clipsContent = false
  if (block.direction === 'row') {
    node.counterAxisAlignItems = 'CENTER'
    node.primaryAxisAlignItems = JUSTIFY[block.align]
  } else {
    node.counterAxisAlignItems = JUSTIFY[block.align]
  }

  const kids = []
  for (const item of CONTENTS[name] || []) {
    if (item.kind === 'mark') {
      const mark = LAYOUT.marks[item.name]
      if (item.name === 'dot') {
        const dot = child(node, 'mark:dot', 'ELLIPSE')
        dot.resize(mark.size, mark.size)
        paint(dot, INK.accent)
        // The glow, as a drop shadow with no offset — the same thing the card's
        // box-shadow is, and the only mark whose value is a blur rather than a
        // rectangle. Its colour is resolved off the accent variable rather than
        // written in, so it follows the ramp like everything else here.
        const accentVar = variableByName.get(INK.accent)
        const rgb = accentVar ? accentVar.resolveForConsumer(dot).value : { r: 1, g: 1, b: 1 }
        dot.effects = [{
          type: 'DROP_SHADOW',
          color: { r: rgb.r, g: rgb.g, b: rgb.b, a: 0.9 },
          offset: { x: 0, y: 0 },
          radius: mark.glow,
          spread: 0,
          visible: true,
          blendMode: 'NORMAL',
        }]
        kids.push(dot)
      } else {
        const rule = child(node, 'mark:rule', 'RECTANGLE')
        rule.resize(mark.width, mark.height)
        rule.cornerRadius = mark.radius
        paint(rule, INK.accent)
        kids.push(rule)
      }
      continue
    }

    if (item.kind === 'chip') {
      const chip = child(node, 'chip', 'FRAME')
      chip.layoutMode = 'HORIZONTAL'
      chip.primaryAxisSizingMode = 'AUTO'
      chip.counterAxisSizingMode = 'AUTO'
      chip.paddingLeft = chip.paddingRight = LAYOUT.marks.chip.padX
      chip.paddingTop = chip.paddingBottom = LAYOUT.marks.chip.padY
      chip.cornerRadius = LAYOUT.marks.chip.radius
      paint(chip, INK.ground)
      chip.fills = chip.fills.map((f) => ({ ...f, opacity: LAYOUT.marks.chip.fill }))
      paint(chip, INK.ink, 'stroke')
      chip.strokes = chip.strokes.map((s) => ({ ...s, opacity: LAYOUT.marks.chip.line }))
      chip.strokeWeight = 1
      const label = child(chip, 'type:chip', 'TEXT')
      label.textAutoResize = 'WIDTH_AND_HEIGHT'
      await style(label, LAYOUT.type.chip)
      label.characters = item.text
      kids.push(chip)
      continue
    }

    const text = child(node, 'type:' + item.name, 'TEXT')
    text.textAutoResize = 'WIDTH_AND_HEIGHT'
    await style(text, LAYOUT.type[item.name])
    text.characters = item.text

    // A measure is a fraction of the block, so the designer resizes the text
    // node itself and the pull reads the fraction back off it.
    const fraction = LAYOUT.type[item.name].measure
    if (fraction != null && block.measure != null) {
      text.textAutoResize = 'HEIGHT'
      text.resize(fraction * block.measure, text.height)
    }
    kids.push(text)
  }

  for (const kid of kids) node.appendChild(kid)
  placed.push({ name, node, block })
}

// Positioned only once every block has laid its children out: a block that hugs
// has no width until then, and a right or bottom anchor is measured from the
// far edge — so placing it first would place it from a width of nothing.
const boxes = {}
for (const { name, node, block } of placed) {
  const [vertical, horizontal] = block.anchor.split('-')
  node.x =
    horizontal === 'left' ? block.offset.x
    : horizontal === 'right' ? REF.width - block.offset.x - node.width
    : (REF.width - node.width) / 2 + block.offset.x
  node.y =
    vertical === 'top' ? block.offset.y
    : vertical === 'bottom' ? REF.height - block.offset.y - node.height
    : (REF.height - node.height) / 2 + block.offset.y
  boxes[name] = { x: node.x, y: node.y, width: node.width, height: node.height }
}

// Back to front, the way the card composites: the artwork, then the type that
// lives *inside* it, then everything the card lays on top. Each is inserted at
// index 0 in turn, so the last one named ends up furthest back.
for (const name of ['block:scene', 'art']) {
  const node = frame.children.find((n) => n.name === name)
  if (node) frame.insertChild(0, node)
}

/* ---------- the typed fields ---------- */

// Everything geometry cannot say, in a panel beside the frame: which edge a
// block hangs from, how its children stack, and the rule that shrinks a long
// headline. Same shape as the card's field rows, and read back the same way.
let panel = page.children.find((n) => n.name === 'og/template fields' && n.type === 'FRAME') || null
if (!panel) {
  panel = figma.createFrame()
  panel.name = 'og/template fields'
  page.appendChild(panel)
  panel.x = frame.x
  panel.y = frame.y + REF.height + 48
}
panel.layoutMode = 'VERTICAL'
panel.primaryAxisSizingMode = 'AUTO'
panel.counterAxisSizingMode = 'FIXED'
panel.resize(REF.width, Math.max(1, panel.height))
panel.itemSpacing = 6
panel.paddingTop = panel.paddingBottom = panel.paddingLeft = panel.paddingRight = 24
panel.cornerRadius = 16
paint(panel, 'theme/surface')

const wanted = new Set(FIELDS.map((f) => 'field:' + f.key))
for (const stale of panel.children.filter((n) => !wanted.has(n.name))) stale.remove()

for (const field of FIELDS) {
  const row = child(panel, 'field:' + field.key, 'FRAME')
  row.layoutMode = 'HORIZONTAL'
  row.primaryAxisSizingMode = 'FIXED'
  row.counterAxisSizingMode = 'AUTO'
  row.itemSpacing = 12
  row.fills = []
  row.layoutSizingHorizontal = 'FILL'

  const label = child(row, 'label', 'TEXT')
  label.fontName = FONTS.mono
  label.fontSize = 11
  label.textAutoResize = 'WIDTH_AND_HEIGHT'
  label.characters = field.key.slice('layout.'.length)
  label.textAutoResize = 'HEIGHT'
  label.resize(300, label.height)
  paint(label, 'theme/text-faint')
  label.layoutSizingHorizontal = 'FIXED'

  const value = child(row, 'value', 'TEXT')
  value.fontName = FONTS.sans
  value.fontSize = 12
  value.textAutoResize = 'WIDTH_AND_HEIGHT'
  value.characters = field.value === '' ? ' ' : field.value
  paint(value, 'theme/text-body')

  row.appendChild(label)
  row.appendChild(value)
}

const themeCollection = (await figma.variables.getLocalVariableCollectionsAsync()).find((c) => c.name === 'theme')
repaint(frame, themeCollection)
repaint(panel, themeCollection)

figma.currentPage.selection = [frame]

return {
  pageId: page.id,
  frameId: frame.id,
  panelId: panel.id,
  created,
  boxes,
  missingFonts,
  missingVariables: [...missingVariables],
  problems,
}
`
}

/**
 * The read-back program.
 *
 * Geometry is measured off the canvas; the typed fields are read out of the
 * panel. Only keys the layout already declares are returned, so a layer someone
 * renames becomes a *missing* key rather than an orphan field invented in
 * Figma — the layout's shape is the code's to decide.
 */
function snapshotScript(layout: Layout, keys: string[], where: Target) {
	return `// generated by scripts/figma-template.ts — do not edit
const LAYOUT = ${JSON.stringify(layout)}
const KEYS = ${JSON.stringify(keys)}
const PAGE_ID = ${JSON.stringify(where.pageId)}
const FRAME_ID = ${JSON.stringify(where.frameId ?? null)}
const FRAME_NAME = ${JSON.stringify(FRAME_NAME)}
const REF = LAYOUT.reference

const page = await figma.getNodeByIdAsync(PAGE_ID)
if (!page || page.type !== 'PAGE') return { values: {}, missing: ['page ' + PAGE_ID] }
await figma.setCurrentPageAsync(page)

let frame = FRAME_ID ? await figma.getNodeByIdAsync(FRAME_ID) : null
if (frame && frame.removed) frame = null
if (!frame) frame = page.children.find((n) => n.name === FRAME_NAME && n.type === 'FRAME') || null
if (!frame) return { values: {}, missing: [FRAME_NAME] }

const values = {}
const missing = []
const notes = []

// The template is the reference box by definition. A resized frame would make
// every number in it mean something else, so it stops the read rather than
// quietly rescaling the layout.
if (Math.round(frame.width) !== REF.width || Math.round(frame.height) !== REF.height) {
  return {
    values: {},
    missing: [],
    notes: ['template is ' + Math.round(frame.width) + '×' + Math.round(frame.height) +
      ', expected ' + REF.width + '×' + REF.height + '. Resize it back, or change reference in og/layout/card.json.'],
  }
}

const px = (n) => String(Math.round(n * 10) / 10)
const frac = (n) => String(Math.round(n * 10000) / 10000)

/* ---------- geometry ---------- */

for (const [name, block] of Object.entries(LAYOUT.blocks)) {
  const node = frame.children.find((n) => n.name === 'block:' + name)
  if (!node) { missing.push('block:' + name); continue }

  const [vertical, horizontal] = block.anchor.split('-')
  const x =
    horizontal === 'left' ? node.x
    : horizontal === 'right' ? REF.width - node.x - node.width
    : node.x - (REF.width - node.width) / 2
  const y =
    vertical === 'top' ? node.y
    : vertical === 'bottom' ? REF.height - node.y - node.height
    : node.y - (REF.height - node.height) / 2

  values['layout.blocks.' + name + '.offset.x'] = px(x)
  values['layout.blocks.' + name + '.offset.y'] = px(y)
  values['layout.blocks.' + name + '.gap'] = px(node.itemSpacing)
  // A hugging block has no measure to report: its width is its content's.
  values['layout.blocks.' + name + '.measure'] = block.measure == null ? '' : px(node.width)

  for (const text of node.findAllWithCriteria({ types: ['TEXT'] })) {
    if (text.name.indexOf('type:') !== 0) continue
    const key = text.name.slice('type:'.length)
    const spec = LAYOUT.type[key]
    if (!spec) continue

    values['layout.type.' + key + '.size'] = px(text.fontSize)

    if (spec.tracking !== undefined) {
      const ls = text.letterSpacing
      values['layout.type.' + key + '.tracking'] =
        frac(ls.unit === 'PERCENT' ? ls.value / 100 : ls.value / text.fontSize)
    }
    if (spec.leading !== undefined) {
      const lh = text.lineHeight
      values['layout.type.' + key + '.leading'] =
        lh.unit === 'AUTO' ? String(spec.leading) : frac(lh.unit === 'PERCENT' ? lh.value / 100 : lh.value / text.fontSize)
    }
    if (spec.measure !== undefined && block.measure != null) {
      values['layout.type.' + key + '.measure'] = frac(text.width / node.width)
    }
    if (spec.opacity !== undefined) values['layout.type.' + key + '.opacity'] = frac(text.opacity)
  }
}

/* ---------- marks ---------- */

const dot = frame.findOne((n) => n.name === 'mark:dot')
if (dot) {
  values['layout.marks.dot.size'] = px(dot.width)
  // A blur radius is the one mark that is an effect rather than a rectangle.
  const glow = (dot.effects || []).find((e) => e.type === 'DROP_SHADOW')
  if (glow) values['layout.marks.dot.glow'] = px(glow.radius)
}
const rule = frame.findOne((n) => n.name === 'mark:rule')
if (rule) {
  values['layout.marks.rule.width'] = px(rule.width)
  values['layout.marks.rule.height'] = px(rule.height)
  values['layout.marks.rule.radius'] = px(typeof rule.cornerRadius === 'number' ? rule.cornerRadius : LAYOUT.marks.rule.radius)
}
const chip = frame.findOne((n) => n.name === 'chip')
if (chip) {
  values['layout.marks.chip.padX'] = px(chip.paddingLeft)
  values['layout.marks.chip.padY'] = px(chip.paddingTop)
  values['layout.marks.chip.radius'] = px(typeof chip.cornerRadius === 'number' ? chip.cornerRadius : LAYOUT.marks.chip.radius)
}

/* ---------- the typed fields ---------- */

const panel = page.children.find((n) => n.name === 'og/template fields')
if (panel) {
  for (const row of panel.children) {
    if (row.name.indexOf('field:') !== 0) continue
    const key = row.name.slice('field:'.length)
    const value = (row.children || []).find((n) => n.name === 'value')
    if (!value) continue
    values[key] = value.characters === ' ' ? '' : value.characters
  }
} else {
  notes.push('no field panel — anchors and the headline rule were not read back')
}

/* Only what the layout declares. */
const known = new Set(KEYS)
for (const key of Object.keys(values)) if (!known.has(key)) delete values[key]
for (const key of KEYS) if (!(key in values)) missing.push(key)

return { values, missing, notes, frameId: frame.id }
`
}

/* ----------------------------------------------------------------- the CLI */

interface Target {
	pageId: string
	frameId?: string
}

type StateWithTemplate = SyncState & {
	og?: { pageId: string; rootId?: string; templates: Record<string, unknown> }
	template?: { pageId: string; frameId: string; panelId?: string }
}

async function readLayout() {
	return JSON.parse(await readFile(LAYOUT_PATH, 'utf8')) as Layout
}

function renderReport(id: string, entries: Entry[], policy: Policy, applied: boolean) {
	const counts = summarise(entries)
	const lines = [
		`# Layout sync ${id}`,
		'',
		`Direction: Figma -> code. ${entries.length} entr${entries.length === 1 ? 'y' : 'ies'}.`,
		'',
		'| outcome | count |',
		'| --- | --- |',
		...Object.entries(counts).map(([k, n]) => `| ${k} | ${n} |`),
		'',
	]

	const label = (key: string) => `\`${key.slice(`${SCOPE}.`.length)}\`${isGeometry(key) ? ' _(dragged)_' : ''}`

	const section = (title: string, kinds: string[], body: (e: Entry) => string) => {
		const hits = entries.filter((e) => kinds.includes(e.verdict.kind))
		if (!hits.length) return
		lines.push(`## ${title}`, '')
		for (const e of hits) lines.push(`- ${body(e)}`)
		lines.push('')
	}

	section('Pulled from Figma', ['pull'], (e) => {
		const v = e.verdict as { kind: 'pull'; value: string }
		return `${label(e.key)} -> \`${v.value || '(none)'}\``
	})
	section('Resolved by policy', ['resolved'], (e) => {
		const v = e.verdict as { kind: 'resolved'; winner: string; ours: string; theirs: string }
		return `${label(e.key)}: code \`${v.ours}\` vs Figma \`${v.theirs}\` — **${v.winner}** won`
	})
	section('Conflicts — need a decision', ['conflict'], (e) => {
		const v = e.verdict as { kind: 'conflict'; ours: string; theirs: string }
		return `${label(e.key)}: code \`${v.ours}\` vs Figma \`${v.theirs}\``
	})
	section('Only in the layout', ['create'], (e) => `${label(e.key)} — push to draw it`)
	section('Only in Figma', ['orphan'], (e) => `${label(e.key)} — no such field in og/layout/card.json`)

	lines.push(
		'',
		'A layout change moves every card. Re-render with `pnpm og:demo` afterwards,',
		'then `pnpm figma:og` to send the new artwork back.',
		'',
		applied ? 'Edits were applied to `og/layout/card.json`.' : 'No files were changed. Re-run with `--apply` to write them.',
		'',
	)
	return lines.join('\n')
}

async function main() {
	const state = (await readState()) as StateWithTemplate
	const layout = await readLayout()
	const values = flatten(layout)

	const record = flag('record')
	if (record) {
		const result = JSON.parse(await readFile(resolve(process.cwd(), record), 'utf8')) as {
			pageId: string
			frameId: string
			panelId?: string
			problems?: string[]
			missingVariables?: string[]
			missingFonts?: string[]
		}

		state.template = {
			pageId: result.pageId,
			frameId: result.frameId,
			...(result.panelId ? { panelId: result.panelId } : {}),
		}

		/* Same reason as the card push: a push makes both sides agree, so the
		   values it wrote are the base the next diff measures movement against. */
		const entries: Entry[] = Object.entries(values).map(([key, value]) => ({ key, verdict: { kind: 'push', value } }))
		state.lastSync = {
			syncId: syncId(new Date()),
			at: new Date().toISOString(),
			values: nextBase(state.lastSync?.values ?? {}, entries),
		}
		state.prefer = { [SCOPE]: 'ask', ...state.prefer }

		await writeState(state)
		console.log(`figma-template: recorded frame ${result.frameId} -> figma/sync.json`)
		console.log(`  base advanced with ${entries.length} layout values`)
		for (const problem of result.problems ?? []) console.log(`  ! ${problem}`)
		for (const name of result.missingVariables ?? []) console.log(`  ! no variable named ${name}`)
		for (const name of result.missingFonts ?? []) console.log(`  ! font unavailable: ${name}`)
		console.log(`\nUpload the backdrop with upload_assets: ${SAMPLE.art} -> the frame's \`art\` node`)
		return
	}

	const pull = flag('pull')
	if (pull) {
		const snapshot = JSON.parse(await readFile(resolve(process.cwd(), pull), 'utf8')) as {
			values: Values
			missing?: string[]
			notes?: string[]
		}

		const override = flag('prefer') as 'code' | 'figma' | undefined
		if (override && override !== 'code' && override !== 'figma') {
			throw new Error(`--prefer must be code or figma, received "${override}"`)
		}

		const policy: Policy = {
			prefer: state.prefer,
			derived: state.derived,
			...(override ? { override } : {}),
		}

		const entries = reconcile(state.lastSync?.values ?? {}, values, snapshot.values, policy)
		const id = syncId(new Date())
		const apply = has('apply')

		const report = renderReport(id, entries, policy, apply)
		const out = reportPath(id)
		await mkdir(dirname(out), { recursive: true })
		await writeFile(out, report, 'utf8')

		if (apply) {
			const edits = entries.flatMap((entry) => {
				if (entry.verdict.kind === 'pull') return [{ key: entry.key, value: entry.verdict.value }]
				if (entry.verdict.kind === 'resolved' && entry.verdict.winner === 'figma') {
					return [{ key: entry.key, value: entry.verdict.value }]
				}
				return []
			})

			if (edits.length) {
				await writeFile(LAYOUT_PATH, applyEdits(await readFile(LAYOUT_PATH, 'utf8'), edits), 'utf8')
				console.log(`  wrote ${edits.length} value(s) -> og/layout/card.json`)
			}

			state.lastSync = {
				syncId: id,
				at: new Date().toISOString(),
				values: nextBase(state.lastSync?.values ?? {}, entries),
			}
			await writeState(state)
		}

		const counts = summarise(entries)
		console.log(`figma-template: ${entries.length} entries -> ${out}`)
		for (const [kind, n] of Object.entries(counts)) console.log(`  ${kind}: ${n}`)
		if (!entries.length) console.log('  no drift')
		for (const key of snapshot.missing ?? []) console.log(`  ! ${key} was not found in the template`)
		for (const note of snapshot.notes ?? []) console.log(`  ! ${note}`)
		if (!apply && entries.length) console.log('\nDry run. Re-run with --apply to write the layout and advance the base.')
		if (apply && entries.length) console.log('\nRe-render with `pnpm og:demo` — the layout moved, so every card did.')

		if (entries.some((e) => e.verdict.kind === 'conflict')) process.exitCode = 1
		return
	}

	const where: Target = {
		pageId: state.template?.pageId ?? state.og?.pageId ?? flag('page') ?? state.pageId,
		...(state.template?.frameId ? { frameId: state.template.frameId } : {}),
	}

	/* Only the keys geometry cannot express become typed rows. */
	const fields = Object.fromEntries(Object.entries(values).filter(([key]) => !isGeometry(key)))

	await mkdir(dirname(OUT_PATH), { recursive: true })
	await writeFile(OUT_PATH, pluginScript(layout, fields, where), 'utf8')
	if (has('snapshot')) await writeFile(SNAPSHOT_PATH, snapshotScript(layout, Object.keys(values), where), 'utf8')

	console.log(describe(values))
	console.log(`  reference box ${layout.reference.width}×${layout.reference.height}`)
	console.log(`\nfigma-template: ${OUT_PATH.replace(`${process.cwd()}/`, '')}`)
	console.log(`  file ${state.fileKey}, page ${where.pageId}, frame "${FRAME_NAME}" ${where.frameId ?? '(new)'}`)
	console.log(`\nRun ${join('dist', 'figma-template.js')} via use_figma, then:`)
	console.log(`  pnpm figma:template --record <result.json>`)
}

await main()
