/**
 * figma-push — generates the Plugin API script that upserts tokens as Figma
 * variables, and prints it for `use_figma` to execute.
 *
 * The MCP tools are agent-facing, not callable from Node, so this script is
 * codegen plus policy: it decides *what* should exist in Figma, emits a
 * self-contained program that makes it so, and that program hands back the ids
 * and values it settled on. `figma-push.ts --record <file>` then folds those
 * back into `figma/sync.json`.
 *
 * Splitting it this way keeps every decision testable offline and leaves the
 * network round trip as a dumb pipe.
 *
 *   pnpm figma:push                 # emit dist/figma-push.js + a summary
 *   pnpm figma:push --scopes=brand,fonts
 *   pnpm figma:push --record out.json
 */
import { readFile, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'

import { flag } from './figma/args.js'
import { nextBase, type ValueMap } from './figma/reconcile.js'
import { readState, writeState, syncId } from './figma/state.js'

interface PlanToken {
	key: string
	collection: string
	figmaName: string
	type: 'COLOR' | 'FLOAT' | 'STRING'
	scopes: string[]
	codeSyntax: string
	value?: unknown
	aliasOf?: string
}

const PLAN_PATH = resolve(process.cwd(), 'dist', 'figma-tokens.json')
const OUT_PATH = resolve(process.cwd(), 'dist', 'figma-push.js')


/**
 * Emits the program that runs *inside* Figma.
 *
 * The plan is inlined as a literal rather than fetched, because the plugin
 * sandbox has no filesystem and no network to this repo. Everything the program
 * needs travels with it.
 */
const TYPE_CODE = { COLOR: 'C', FLOAT: 'F', STRING: 'S' } as const

/**
 * Compacts the plan for transport.
 *
 * Only `scopes` is policy; `figmaName`, `codeSyntax` and `collection` are
 * mechanical rewrites of the key, and an sRGB hex reconstructs r/g/b exactly.
 * Sending them anyway costs ~3× the payload — which matters because the script
 * is pasted into a tool call with a hard size limit, and every byte is a byte
 * that can be transcribed wrong.
 *
 * Scope arrays repeat across a hundred ramp steps, so they are deduplicated
 * into a table and referenced by index.
 */
function compact(tokens: PlanToken[]) {
	const scopeTable: string[][] = []
	const scopeIndex = (scopes: string[]) => {
		const encoded = scopes.join(',')
		let i = scopeTable.findIndex((s) => s.join(',') === encoded)
		if (i === -1) i = scopeTable.push(scopes) - 1
		return i
	}

	const rows = tokens.map((t) => {
		const base = [t.key, TYPE_CODE[t.type], scopeIndex(t.scopes)]
		if (t.aliasOf) return [...base, null, t.aliasOf]
		const value = t.type === 'COLOR' ? (t.value as { hex: string }).hex : t.value
		return [...base, value]
	})

	return { scopeTable, rows }
}

function pluginScript(tokens: PlanToken[], known: Record<string, { id: string }>) {
	const { scopeTable, rows } = compact(tokens)

	return `// generated by scripts/figma-push.ts — do not edit
const SCOPES = ${JSON.stringify(scopeTable)}
const ROWS = ${JSON.stringify(rows)}
const KNOWN = ${JSON.stringify(known)}

const TYPES = { C: 'COLOR', F: 'FLOAT', S: 'STRING' }
const hexToRgb = (h) => ({
  r: parseInt(h.slice(1, 3), 16) / 255,
  g: parseInt(h.slice(3, 5), 16) / 255,
  b: parseInt(h.slice(5, 7), 16) / 255,
  a: 1,
})

// Rehydrated here rather than sent: every field below is a mechanical rewrite
// of the key, so deriving them cannot drift from what the emitter decided.
const PLAN = ROWS.map(([key, code, scopeIdx, value, aliasOf]) => ({
  key,
  collection: key.split('.')[0],
  figmaName: key.replace(/\\./g, '/'),
  type: TYPES[code],
  scopes: SCOPES[scopeIdx],
  codeSyntax: 'var(--' + key.replace(/\\./g, '-') + ')',
  value: code === 'C' && value != null ? { ...hexToRgb(value), hex: value } : value,
  aliasOf,
}))

const collections = {}
const modes = {}
const collectionObjects = {}
const variables = {}
const variableObjects = {}
const values = {}
const created = []
const updated = []

const existingCollections = await figma.variables.getLocalVariableCollectionsAsync()

for (const name of [...new Set(PLAN.map((t) => t.collection))]) {
  let collection = existingCollections.find((c) => c.name === name)
  if (!collection) {
    collection = figma.variables.createVariableCollection(name)
    // One mode. The design book defines no theming, so inventing Light/Dark here
    // would put a decision in Figma that code cannot express.
    collection.renameMode(collection.modes[0].modeId, 'Value')
  }
  collectionObjects[name] = collection
  collections[name] = collection.id
  modes[name] = collection.modes[0].modeId
}

// Fetched once, then bucketed. Calling this per collection re-reads every
// variable in the file for each one.
const allExisting = await figma.variables.getLocalVariablesAsync()
const byCollection = {}
for (const [name, id] of Object.entries(collections)) {
  byCollection[name] = allExisting.filter((v) => v.variableCollectionId === id)
}

// PLAN order is dependency-safe: an alias target always appears before the
// variable that points at it, so this single pass never dangles.
for (const token of PLAN) {
  const modeId = modes[token.collection]

  let variable = null
  const recorded = KNOWN[token.key]
  if (recorded) variable = await figma.variables.getVariableByIdAsync(recorded.id)
  if (!variable) variable = byCollection[token.collection].find((v) => v.name === token.figmaName) || null

  if (variable) {
    // The recorded id wins over the name, so a rename in Figma is followed
    // rather than silently undone by re-creating the old name.
    if (variable.name !== token.figmaName) variable.name = token.figmaName
    updated.push(token.key)
  } else {
    variable = figma.variables.createVariable(token.figmaName, collectionObjects[token.collection], token.type)
    byCollection[token.collection].push(variable)
    created.push(token.key)
  }

  if (token.aliasOf) {
    // Alias targets may live outside this push — a ramp seed points at its
    // brand colour, radius/base at brand/radius. Try this run, then the
    // recorded ids, then the file itself before giving up.
    let targetVar = variableObjects[token.aliasOf] || null
    if (!targetVar && KNOWN[token.aliasOf]) {
      targetVar = await figma.variables.getVariableByIdAsync(KNOWN[token.aliasOf].id)
    }
    if (!targetVar) {
      const targetName = token.aliasOf.replace(/\./g, '/')
      targetVar = allExisting.find((v) => v.name === targetName) || null
    }
    if (!targetVar) throw new Error('alias target not found: ' + token.aliasOf)
    variable.setValueForMode(modeId, figma.variables.createVariableAlias(targetVar))
    values[token.key] = values[token.aliasOf] ?? String(targetVar.valuesByMode[Object.keys(targetVar.valuesByMode)[0]])
  } else if (token.type === 'COLOR') {
    const { r, g, b, a } = token.value
    variable.setValueForMode(modeId, { r, g, b, a })
    values[token.key] = token.value.hex
  } else {
    variable.setValueForMode(modeId, token.value)
    values[token.key] = String(token.value)
  }

  // Never ALL_SCOPES — an unscoped variable pollutes every property picker.
  variable.scopes = token.scopes
  variable.setVariableCodeSyntax('WEB', token.codeSyntax)

  // Collections carry no description, so the "don't edit this here" signal has
  // to live on each variable. Ramp steps are computed by rampStops(); an edit
  // in Figma cannot be expressed in the book and dies on the next build.
  if (token.collection === 'ramp') {
    const seed = token.aliasOf ? token.aliasOf : 'brand/' + token.key.slice(5).split('-')[0]
    variable.description = 'Generated from ' + seed.replace(/\\./g, '/') + ' by rampStops(). Edit the design book, not this.'
  }
  variables[token.key] = variable.id
  variableObjects[token.key] = variable
}

return {
  collections,
  modes,
  variables,
  values,
  createdNodeIds: Object.values(variables),
  created: created.length,
  updated: updated.length,
}
`
}

async function main() {
	const state = await readState()

	/*
	 * M1 pushes the authored scopes only. Widening to `ramp` is a flag change.
	 *
	 * `family` has to travel with `brand`: `brand.headline` aliases
	 * `family.serif`, and while the push can resolve a target that already has a
	 * recorded id, the very first push of the pair would dangle without it.
	 */
	const scopes = (flag('scopes') ?? 'family,brand,fonts').split(',')

	let plan: { tokens: PlanToken[] }
	try {
		plan = JSON.parse(await readFile(PLAN_PATH, 'utf8'))
	} catch {
		throw new Error(`${PLAN_PATH} not found. Run \`pnpm figma:emit\` first.`)
	}

	const tokens = plan.tokens.filter((t) => scopes.includes(t.collection))
	if (tokens.length === 0) throw new Error(`No tokens matched scopes: ${scopes.join(', ')}`)

	/* Recording the result of an executed push rather than emitting a new one. */
	const record = flag('record')
	if (record) {
		const result = JSON.parse(await readFile(resolve(process.cwd(), record), 'utf8')) as {
			collections: Record<string, string>
			modes: Record<string, string>
			variables: Record<string, string>
			values: ValueMap
		}

		const id = syncId(new Date())
		state.collections = { ...state.collections, ...result.collections }
		state.modes = { ...state.modes, ...result.modes }
		for (const [key, variableId] of Object.entries(result.variables)) {
			const token = tokens.find((t) => t.key === key)
			state.variables[key] = { id: variableId, collection: token?.collection ?? 'brand' }
		}

		/*
		 * An aliased variable has no literal of its own, so the push reports it as
		 * null. Storing that would make the token compare as changed on the very
		 * next sync — a false conflict of exactly the kind the base exists to
		 * prevent. Resolve it to whatever backs the alias instead.
		 */
		const merged: ValueMap = { ...(state.lastSync?.values ?? {}), ...result.values }
		const resolveAlias = (key: string, depth = 0): string | undefined => {
			if (depth > 10) throw new Error(`alias cycle resolving ${key}`)
			const direct = merged[key]
			if (direct != null) return direct
			const target = plan.tokens.find((t) => t.key === key)?.aliasOf
			return target ? resolveAlias(target, depth + 1) : undefined
		}

		const entries = Object.entries(result.values).map(([key, value]) => {
			const resolved = value ?? resolveAlias(key)
			if (resolved == null) throw new Error(`no value recorded for ${key} and its alias chain is unresolved`)
			return { key, verdict: { kind: 'push' as const, value: resolved } }
		})
		state.lastSync = {
			syncId: id,
			at: new Date().toISOString(),
			values: nextBase(state.lastSync?.values ?? {}, entries),
		}

		await writeState(state)
		console.log(`figma-push: recorded ${Object.keys(result.variables).length} variables -> figma/sync.json`)
		console.log(`  base advanced to ${Object.keys(state.lastSync.values).length} values (syncId ${id})`)
		return
	}

	/*
	 * Recorded ids for the tokens being pushed, plus any alias target they point
	 * at. Without the targets, a scoped push (`--scopes=radius`) couldn't resolve
	 * `radius.base -> brand.radius` and would fail on a cross-collection alias.
	 */
	const aliasTargets = new Set(tokens.map((t) => t.aliasOf).filter(Boolean) as string[])
	const known = Object.fromEntries(
		Object.entries(state.variables).filter(
			([key]) => tokens.some((t) => t.key === key) || aliasTargets.has(key),
		),
	)

	await writeFile(OUT_PATH, pluginScript(tokens, known), 'utf8')

	console.log(`figma-push: ${tokens.length} tokens (${scopes.join(', ')}) -> ${OUT_PATH}`)
	console.log(`  file ${state.fileKey}`)
	console.log(`  ${Object.keys(known).length} already have recorded ids; the rest will be created`)
	console.log(`  aliases: ${tokens.filter((t) => t.aliasOf).map((t) => `${t.key} -> ${t.aliasOf}`).join(', ') || 'none'}`)
	console.log(`\nRun ${join('dist', 'figma-push.js')} via use_figma, then:`)
	console.log(`  pnpm figma:push --record <result.json>`)
}

await main()
