/**
 * figma-push — generates the Plugin API script that upserts tokens as Figma
 * variables, and prints it for `use_figma` to execute.
 *
 * The MCP tools are agent-facing, not callable from Node, so this script is
 * codegen plus policy: it decides *what* should exist in Figma, emits a
 * self-contained program that makes it so, and that program hands back the ids
 * and values it settled on. `figma-push.ts --record <file>` then folds those
 * back into `figma/sync.json`.
 *
 * Splitting it this way keeps every decision testable offline and leaves the
 * network round trip as a dumb pipe.
 *
 *   pnpm figma:push                 # emit dist/figma-push.js + a summary
 *   pnpm figma:push --scopes=brand,fonts
 *   pnpm figma:push --record out.json
 */
import { readFile, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'

import { nextBase, type ValueMap } from './figma/reconcile.js'
import { readState, writeState, syncId } from './figma/state.js'

interface PlanToken {
	key: string
	collection: string
	figmaName: string
	type: 'COLOR' | 'FLOAT' | 'STRING'
	scopes: string[]
	codeSyntax: string
	value?: unknown
	aliasOf?: string
}

const PLAN_PATH = resolve(process.cwd(), 'dist', 'figma-tokens.json')
const OUT_PATH = resolve(process.cwd(), 'dist', 'figma-push.js')

function flag(name: string) {
	const hit = process.argv.find((a) => a.startsWith(`--${name}=`))
	return hit ? hit.slice(name.length + 3) : undefined
}

/**
 * Emits the program that runs *inside* Figma.
 *
 * The plan is inlined as a literal rather than fetched, because the plugin
 * sandbox has no filesystem and no network to this repo. Everything the program
 * needs travels with it.
 */
function pluginScript(tokens: PlanToken[], known: Record<string, { id: string }>) {
	return `// generated by scripts/figma-push.ts — do not edit
const PLAN = ${JSON.stringify(tokens)}
const KNOWN = ${JSON.stringify(known)}

const collections = {}
const modes = {}
const collectionObjects = {}
const variables = {}
const variableObjects = {}
const values = {}
const created = []
const updated = []

const existingCollections = await figma.variables.getLocalVariableCollectionsAsync()

for (const name of [...new Set(PLAN.map((t) => t.collection))]) {
  let collection = existingCollections.find((c) => c.name === name)
  if (!collection) {
    collection = figma.variables.createVariableCollection(name)
    // One mode. The design book defines no theming, so inventing Light/Dark here
    // would put a decision in Figma that code cannot express.
    collection.renameMode(collection.modes[0].modeId, 'Value')
  }
  collectionObjects[name] = collection
  collections[name] = collection.id
  modes[name] = collection.modes[0].modeId
}

// Fetched once, then bucketed. Calling this per collection re-reads every
// variable in the file for each one.
const allExisting = await figma.variables.getLocalVariablesAsync()
const byCollection = {}
for (const [name, id] of Object.entries(collections)) {
  byCollection[name] = allExisting.filter((v) => v.variableCollectionId === id)
}

// PLAN order is dependency-safe: an alias target always appears before the
// variable that points at it, so this single pass never dangles.
for (const token of PLAN) {
  const modeId = modes[token.collection]

  let variable = null
  const recorded = KNOWN[token.key]
  if (recorded) variable = await figma.variables.getVariableByIdAsync(recorded.id)
  if (!variable) variable = byCollection[token.collection].find((v) => v.name === token.figmaName) || null

  if (variable) {
    // The recorded id wins over the name, so a rename in Figma is followed
    // rather than silently undone by re-creating the old name.
    if (variable.name !== token.figmaName) variable.name = token.figmaName
    updated.push(token.key)
  } else {
    variable = figma.variables.createVariable(token.figmaName, collectionObjects[token.collection], token.type)
    byCollection[token.collection].push(variable)
    created.push(token.key)
  }

  if (token.aliasOf) {
    // Alias targets may live outside this push — a ramp seed points at its
    // brand colour, radius/base at brand/radius. Try this run, then the
    // recorded ids, then the file itself before giving up.
    let targetVar = variableObjects[token.aliasOf] || null
    if (!targetVar && KNOWN[token.aliasOf]) {
      targetVar = await figma.variables.getVariableByIdAsync(KNOWN[token.aliasOf].id)
    }
    if (!targetVar) {
      const targetName = token.aliasOf.replace(/\./g, '/')
      targetVar = allExisting.find((v) => v.name === targetName) || null
    }
    if (!targetVar) throw new Error('alias target not found: ' + token.aliasOf)
    variable.setValueForMode(modeId, figma.variables.createVariableAlias(targetVar))
    values[token.key] = values[token.aliasOf] ?? String(targetVar.valuesByMode[Object.keys(targetVar.valuesByMode)[0]])
  } else if (token.type === 'COLOR') {
    const { r, g, b, a } = token.value
    variable.setValueForMode(modeId, { r, g, b, a })
    values[token.key] = token.value.hex
  } else {
    variable.setValueForMode(modeId, token.value)
    values[token.key] = String(token.value)
  }

  // Never ALL_SCOPES — an unscoped variable pollutes every property picker.
  variable.scopes = token.scopes
  variable.setVariableCodeSyntax('WEB', token.codeSyntax)
  variables[token.key] = variable.id
  variableObjects[token.key] = variable
}

return {
  collections,
  modes,
  variables,
  values,
  createdNodeIds: Object.values(variables),
  created: created.length,
  updated: updated.length,
}
`
}

async function main() {
	const state = await readState()

	/* M1 pushes the authored scopes only. Widening to `ramp` is a flag change. */
	const scopes = (flag('scopes') ?? 'brand,fonts').split(',')

	let plan: { tokens: PlanToken[] }
	try {
		plan = JSON.parse(await readFile(PLAN_PATH, 'utf8'))
	} catch {
		throw new Error(`${PLAN_PATH} not found. Run \`pnpm figma:emit\` first.`)
	}

	const tokens = plan.tokens.filter((t) => scopes.includes(t.collection))
	if (tokens.length === 0) throw new Error(`No tokens matched scopes: ${scopes.join(', ')}`)

	/* Recording the result of an executed push rather than emitting a new one. */
	const record = flag('record')
	if (record) {
		const result = JSON.parse(await readFile(resolve(process.cwd(), record), 'utf8')) as {
			collections: Record<string, string>
			modes: Record<string, string>
			variables: Record<string, string>
			values: ValueMap
		}

		const id = syncId(new Date())
		state.collections = { ...state.collections, ...result.collections }
		state.modes = { ...state.modes, ...result.modes }
		for (const [key, variableId] of Object.entries(result.variables)) {
			const token = tokens.find((t) => t.key === key)
			state.variables[key] = { id: variableId, collection: token?.collection ?? 'brand' }
		}

		/*
		 * The base advances on push, not only on pull. Skipping this is what makes
		 * the next sync see both sides differing from a stale base and report a
		 * conflict that never happened.
		 */
		const entries = Object.entries(result.values).map(([key, value]) => ({
			key,
			verdict: { kind: 'push' as const, value },
		}))
		state.lastSync = {
			syncId: id,
			at: new Date().toISOString(),
			values: nextBase(state.lastSync?.values ?? {}, entries),
		}

		await writeState(state)
		console.log(`figma-push: recorded ${Object.keys(result.variables).length} variables -> figma/sync.json`)
		console.log(`  base advanced to ${Object.keys(state.lastSync.values).length} values (syncId ${id})`)
		return
	}

	/*
	 * Recorded ids for the tokens being pushed, plus any alias target they point
	 * at. Without the targets, a scoped push (`--scopes=radius`) couldn't resolve
	 * `radius.base -> brand.radius` and would fail on a cross-collection alias.
	 */
	const aliasTargets = new Set(tokens.map((t) => t.aliasOf).filter(Boolean) as string[])
	const known = Object.fromEntries(
		Object.entries(state.variables).filter(
			([key]) => tokens.some((t) => t.key === key) || aliasTargets.has(key),
		),
	)

	await writeFile(OUT_PATH, pluginScript(tokens, known), 'utf8')

	console.log(`figma-push: ${tokens.length} tokens (${scopes.join(', ')}) -> ${OUT_PATH}`)
	console.log(`  file ${state.fileKey}`)
	console.log(`  ${Object.keys(known).length} already have recorded ids; the rest will be created`)
	console.log(`  aliases: ${tokens.filter((t) => t.aliasOf).map((t) => `${t.key} -> ${t.aliasOf}`).join(', ') || 'none'}`)
	console.log(`\nRun ${join('dist', 'figma-push.js')} via use_figma, then:`)
	console.log(`  pnpm figma:push --record <result.json>`)
}

await main()
